import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, BookOpen } from 'lucide-react';
import { guides } from '../toolsData';
import AdSensePlaceholder from '../components/AdSensePlaceholder';

const guideContent: Record<string, { sections: { title: string; content: string }[] }> = {
  'direitos-trabalhistas': {
    sections: [
      { title: 'O que é a CLT e quais direitos ela garante?', content: 'A Consolidação das Leis do Trabalho (CLT), criada em 1943 pelo Decreto-Lei 5.452, é o principal conjunto de leis que regula as relações trabalhistas no Brasil. A CLT estabelece os direitos e deveres de empregados e empregadores, garantindo proteção ao trabalhador em diversas situações. Ao longo de suas mais de 900 normas, a CLT cobre desde a admissão do funcionário até o momento da rescisão contratual, passando por jornada de trabalho, férias, 13º salário, FGTS, adicionais e muito mais. A CLT também é complementada pela Constituição Federal de 1988, que em seu artigo 7º lista diversos direitos fundamentais dos trabalhadores urbanos e rurais.' },
      { title: 'Jornada de Trabalho: Regras Gerais', content: 'A jornada de trabalho padrão estabelecida pela CLT é de 8 horas diárias e 44 horas semanais, podendo ser reduzida por acordo ou convenção coletiva. A jornada pode ser distribuída de segunda a sábado, com folga preferencial aos domingos. Existem regimes especiais de jornada para categorias específicas, como bancários (6 horas), jornalistas (5 horas) e médicos (4 horas). A CLT também prevê intervalos intrajornada (almoço/descanso) de no mínimo 1 hora para jornadas acima de 6 horas, e de 15 minutos para jornadas entre 4 e 6 horas. O intervalo interjornada (entre o fim de um dia e o início do próximo) deve ser de no mínimo 11 horas consecutivas.' },
      { title: 'Horas Extras: Direitos e Cálculos', content: 'Qualquer hora trabalhada além da jornada contratual deve ser paga como hora extra com adicional mínimo de 50% sobre o valor da hora normal em dias úteis, e 100% em domingos e feriados. As horas extras são limitadas a 2 horas por dia, totalizando no máximo 10 horas diárias de trabalho. Além do pagamento do adicional, as horas extras habituais geram reflexos em outras verbas como DSR, férias, 13º salário e FGTS. Acordos de compensação de jornada (banco de horas) podem flexibilizar esses limites, desde que previstos em acordo coletivo ou individual, conforme a Reforma Trabalhista de 2017.' },
      { title: 'Férias: Direito Constitucional', content: 'Após 12 meses de trabalho (período aquisitivo), o empregado tem direito a 30 dias corridos de férias, que devem ser concedidas nos 12 meses seguintes (período concessivo). O valor das férias corresponde ao salário normal acrescido de 1/3 constitucional. As férias podem ser divididas em até 3 períodos, sendo um deles de no mínimo 14 dias e os demais de no mínimo 5 dias cada. O pagamento das férias deve ser feito até 2 dias antes do início do descanso. Faltas não justificadas ao longo do período aquisitivo podem reduzir os dias de férias: de 6 a 14 faltas = 24 dias, de 15 a 23 = 18 dias, de 24 a 32 = 12 dias, acima de 32 = perde o direito.' },
      { title: '13º Salário: Gratificação Natalina', content: 'O 13º salário, instituído pela Lei 4.090/1962, é pago em duas parcelas: a primeira entre 1º de fevereiro e 30 de novembro (sem descontos de INSS ou IRRF), correspondendo à metade do salário bruto; e a segunda até 20 de dezembro, com descontos de INSS e IRRF sobre o valor total. O valor é proporcional aos meses trabalhados no ano, considerando como mês completo aquele com 15 dias ou mais de trabalho. Horas extras habituais e adicionais integram o cálculo do 13º, assim como o FGTS é devido sobre o valor total do 13º salário.' },
      { title: 'FGTS: Fundo de Garantia', content: 'O FGTS foi criado pela Lei 5.107/1966 e hoje é regido pela Lei 8.036/1990. Mensalmente, o empregador deposita 8% do salário bruto do funcionário em conta vinculada na Caixa Econômica Federal. O saldo é corrigido pela TR mais juros de 3% ao ano. Em caso de dispensa sem justa causa, o trabalhador pode sacar o saldo total e receber multa de 40% paga pelo empregador. O FGTS também pode ser sacado para aposentadoria, compra da casa própria, doenças graves e calamidade pública. O saque-aniversário permite retirada parcial anual, mas implica perda do direito ao saque total em caso de demissão.' },
      { title: 'Rescisão Contratual: Tipos e Direitos', content: 'A rescisão do contrato de trabalho pode ocorrer de diversas formas: dispensa sem justa causa (a mais comum, garantindo todas as verbas rescisórias mais multa de 40% do FGTS e seguro-desemprego), dispensa por justa causa (perde alguns direitos como multa do FGTS e aviso prévio), pedido de demissão (aviso prévio pode ser descontado), rescisão indireta (justa causa do empregador, equiparada à dispensa sem justa causa para todos os efeitos), rescisão por acordo (criada pela Reforma Trabalhista de 2017, com regras específicas) e término de contrato por prazo determinado. Cada modalidade tem regras específicas sobre quais verbas são devidas.' },
      { title: 'Verbas Rescisórias: O Que Você Tem Direito', content: 'Ao ser dispensado sem justa causa, o trabalhador tem direito a: saldo de salário (dias trabalhados no mês da rescisão), aviso prévio (30 a 90 dias conforme tempo de serviço), férias vencidas e proporcionais + 1/3 constitucional, 13º salário proporcional, multa de 40% sobre o saldo do FGTS, saque do FGTS e seguro-desemprego (se cumprir os requisitos). Todas as verbas devem ser pagas em até 10 dias corridos após o término do contrato. O não pagamento no prazo gera multa e correção monetária.' },
      { title: 'Adicionais Salariais: Noturno, Periculosidade e Insalubridade', content: 'A CLT prevê três adicionais principais. O adicional noturno (20% sobre a hora normal para trabalho entre 22h e 5h) com redução da hora noturna para 52min30s. O adicional de periculosidade (30% sobre o salário base) para atividades com inflamáveis, explosivos, energia elétrica e vigilância. O adicional de insalubridade (10%, 20% ou 40% do salário mínimo conforme o grau) para exposição a agentes nocivos à saúde. Todos esses adicionais integram o salário para fins de férias, 13º, FGTS e aviso prévio. A Reforma Trabalhista de 2017 passou a permitir o acúmulo de periculosidade e insalubridade.' },
      { title: 'Licenças e Faltas Justificadas', content: 'A CLT prevê diversas situações em que o trabalhador pode faltar sem desconto no salário: casamento (3 dias consecutivos), falecimento de cônjuge, pai, mãe ou filho (2 dias), doação de sangue (1 dia a cada 12 meses), alistamento militar (1 dia), realização de prova de vestibular ou ENEM (dia da prova), comparecimento como jurado no tribunal do júri (dias necessários), e acompanhamento de filho de até 6 anos em consulta médica (1 dia por ano). Para exames preventivos de câncer, o trabalhador tem direito a 3 dias de falta por ano.' },
      { title: 'Contribuição Sindical: Obrigatória ou Facultativa?', content: 'Desde a Reforma Trabalhista de 2017 (Lei 13.467/2017), a contribuição sindical deixou de ser obrigatória e passou a ser facultativa. O trabalhador só precisa pagar se autorizar previamente o desconto. A contribuição assistencial e a taxa negocial (previstas em convenção coletiva) também dependem de autorização do trabalhador, conforme decidido pelo STF em 2023.' },
      { title: 'Estabilidade no Emprego: Quando o Trabalhador Não Pode ser Demitido', content: 'Existem diversas situações em que o trabalhador tem estabilidade provisória no emprego: gestante (desde a confirmação da gravidez até 5 meses após o parto), membro da CIPA (desde o registro da candidatura até 1 ano após o mandato), empregado acidentado (12 meses após o retorno ao trabalho), dirigente sindical (desde o registro da candidatura até 1 ano após o mandato), e empregado eleito para comissão de conciliação prévia (desde a candidatura até 1 ano após o mandato). Durante o período de estabilidade, o empregado não pode ser dispensado sem justa causa.' },
    ],
  },
  'como-calcular-horas-extras': {
    sections: [
      { title: 'Introdução ao Cálculo de Horas Extras', content: 'O cálculo de horas extras é uma das principais dúvidas dos trabalhadores brasileiros. A CLT determina que horas trabalhadas além da jornada contratual devem ser remuneradas com acréscimo mínimo de 50% em dias úteis e 100% em domingos e feriados. O primeiro passo para calcular é entender sua jornada de trabalho base e o valor da sua hora normal de trabalho. O cálculo envolve algumas etapas que detalharemos a seguir, com exemplos práticos para facilitar o entendimento.' },
      { title: 'Passo 1: Calcule o Valor da Sua Hora Normal', content: 'Para calcular o valor da sua hora normal, divida seu salário mensal pela carga horária mensal. Para a jornada padrão de 44 horas semanais, a carga horária mensal é de 220 horas (44 horas × 5 semanas). Para jornada de 40 horas semanais, use 200 horas. Para jornada de 36 horas, use 180 horas. Exemplo prático: salário de R$ 2.200,00 com jornada de 44h/semana: R$ 2.200,00 ÷ 220h = R$ 10,00 por hora normal. Este é o valor base para todos os cálculos seguintes.' },
      { title: 'Passo 2: Aplique o Adicional de Hora Extra', content: 'Multiplique o valor da hora normal pelo fator correspondente ao percentual do adicional. Para hora extra com adicional de 50% em dias úteis: multiplique por 1,5. Exemplo: R$ 10,00 × 1,5 = R$ 15,00 por hora extra. Para hora extra com adicional de 100% em domingos e feriados: multiplique por 2,0. Exemplo: R$ 10,00 × 2,0 = R$ 20,00 por hora extra. Se sua convenção coletiva previr percentual maior, como 80%, multiplique por 1,8. Exemplo: R$ 10,00 × 1,8 = R$ 18,00 por hora extra.' },
      { title: 'Passo 3: Multiplique pelo Número de Horas Extras', content: 'Multiplique o valor da hora extra (calculado no Passo 2) pelo total de horas extras realizadas no mês. Exemplo: 10 horas extras a 50% = 10 × R$ 15,00 = R$ 150,00. Se você fez horas extras em dias diferentes com percentuais diferentes, calcule separadamente e some. Exemplo: 8 horas extras a 50% (R$ 120,00) + 4 horas extras a 100% (R$ 80,00) = R$ 200,00 de horas extras no mês.' },
      { title: 'Passo 4: Calcule o Reflexo no DSR', content: 'O DSR (Descanso Semanal Remunerado) incide sobre o total de horas extras do mês. A fórmula é: (Total de Horas Extras ÷ Número de Dias Úteis do Mês) × Número de Domingos e Feriados. Por exemplo: R$ 200,00 de HE ÷ 26 dias úteis = R$ 7,69 por dia útil × 4 domingos = R$ 30,76 de DSR sobre horas extras. O sábado é considerado dia útil para este cálculo. O valor do DSR deve ser adicionado ao salário do mês.' },
      { title: 'Passo 5: Calcule os Descontos e Some Tudo', content: 'O valor total a receber é a soma das horas extras mais o DSR sobre horas extras. Exemplo: R$ 200,00 (HE) + R$ 30,76 (DSR) = R$ 230,76. Este valor será acrescido ao salário normal do mês e sobre ele incidirão os descontos normais de INSS e IRRF (se aplicável). Lembre-se que as horas extras habituais também integram a base de cálculo de férias e 13º salário.' },
      { title: 'Passo 6: Calcule Média para Férias e 13º', content: 'Se você faz horas extras com frequência, elas integram o cálculo de férias e 13º salário. Para férias, some o total de horas extras recebidas nos 12 meses anteriores e divida por 12 para obter a média mensal. Essa média deve ser acrescida ao salário no cálculo das férias. Exemplo: total de R$ 2.760,00 em HE nos 12 meses ÷ 12 = R$ 230,00 de média mensal que integra o valor das férias.' },
      { title: 'Percentuais Especiais por Categoria', content: 'Muitas categorias profissionais possuem percentuais de hora extra maiores que os legais através de convenções coletivas. Por exemplo, bancários geralmente têm 50% para primeiras horas e 100% para demais; metalúrgicos frequentemente têm 70% ou 80%; comerciários podem ter 60% ou 100% em feriados. Consulte sempre o sindicato da sua categoria para verificar o percentual correto aplicável ao seu contrato de trabalho.' },
      { title: 'Cuidados e Direitos Importantes', content: 'A CLT limita as horas extras a 2 horas por dia, totalizando no máximo 10 horas diárias. O banco de horas permite compensar horas extras com folgas em até 6 meses ou 1 ano, dependendo do acordo. Horas extras não pagas geram direito a reclamação trabalhista com prazo prescricional de 5 anos. Mantenha registros pessoais dos horários trabalhados, independentemente do ponto eletrônico da empresa.' },
      { title: 'Calculando Horas Extras com Adicional Noturno', content: 'Se as horas extras forem realizadas em período noturno (22h às 5h), os adicionais se acumulam: adicional noturno de 20% + adicional de hora extra de 50% ou 100%. O cálculo é em cascata: primeiro calcula-se o adicional noturno sobre a hora normal, e depois aplica-se o adicional de hora extra sobre esse valor. Além disso, a hora noturna reduzida de 52 minutos e 30 segundos também se aplica, aumentando o valor devido.' },
    ],
  },
  'diferencas-clt-pj': {
    sections: [
      { title: 'Introdução: CLT vs PJ', content: 'A escolha entre o regime CLT (Consolidação das Leis do Trabalho) e o regime PJ (Pessoa Jurídica) é uma das decisões mais importantes na carreira de um profissional. Cada modelo tem vantagens e desvantagens significativas, e a escolha correta depende de fatores como estabilidade desejada, benefícios, carga tributária e planejamento de carreira. Neste guia completo, analisamos todos os aspectos de cada regime para ajudar você a tomar a melhor decisão.' },
      { title: 'O que é o Regime CLT?', content: 'O regime CLT é o modelo tradicional de contratação no Brasil, regido pela Consolidação das Leis do Trabalho. O trabalhador é contratado como empregado, com carteira assinada, e tem direito a todos os benefícios previstos em lei: 13º salário, férias remuneradas com 1/3 constitucional, FGTS com depósito de 8%, seguro-desemprego, INSS (aposentadoria e benefícios previdenciários), horas extras, adicional noturno, vale-transporte, licença-maternidade/paternidade, estabilidade em algumas situações, e proteção contra dispensa arbitrária. A empresa é responsável por recolher todos os encargos trabalhistas e previdenciários.' },
      { title: 'O que é o Regime PJ?', content: 'No regime PJ, o profissional abre uma empresa (MEI, ME ou EIRELI) e presta serviços como pessoa jurídica. O profissional recebe o valor bruto integral do contrato, sem descontos de INSS ou IRRF na fonte, mas é responsável por pagar seus próprios impostos (DAS do MEI, ISS, IRPJ, PIS, COFINS). O profissional PJ não tem direito a 13º salário, férias remuneradas, FGTS, seguro-desemprego ou outros benefícios CLT. Em compensação, pode deduzir despesas do negócio (como equipamentos, internet, transporte) e tem maior flexibilidade contratual.' },
      { title: 'Comparação Financeira: Quanto Você Realmente Leva?', content: 'Para comparar corretamente, é preciso calcular o valor líquido anual em cada regime. Exemplo: proposta CLT de R$ 8.000,00/mês versus proposta PJ de R$ 12.000,00/mês. Na CLT: 12 salários (R$ 96.000) + 13º (R$ 8.000) + férias + 1/3 (R$ 10.667) + FGTS 8% (R$ 8.320) + INSS patronal (R$ 8.800) ≈ R$ 131.787/ano de custo total. Líquido após INSS/IRRF do funcionário ≈ R$ 97.000/ano. No PJ: R$ 144.000/ano bruto, menos impostos (MEI: ~R$ 2.000/ano; ME Simples: 6-15%) ≈ R$ 122.000-135.000/ano líquido. A diferença líquida anual pode chegar a R$ 25.000-38.000 a favor do PJ, mas sem proteções trabalhistas.' },
      { title: 'Vantagens do Regime CLT', content: 'Proteção trabalhista completa contra demissão arbitrária, estabilidade em situações específicas (gestante, CIPA, acidentado), férias remuneradas com 1/3 constitucional, 13º salário garantido, FGTS com depósito de 8%, seguro-desemprego em caso de demissão involuntária, INSS com acesso a aposentadoria e benefícios previdenciários, horas extras com adicionais legais, adicional noturno, periculosidade e insalubridade conforme o caso, vale-transporte, licença-maternidade de 120 dias (180 em empresas cidadãs) e licença-paternidade de 5 a 20 dias.' },
      { title: 'Vantagens do Regime PJ', content: 'Remuneração líquida geralmente 20-40% maior que CLT para o mesmo custo ao contratante, maior flexibilidade de horário e contrato, possibilidade de negociar valores por projeto ou hora técnica, dedução de despesas operacionais do negócio (equipamentos, internet, telefone, transporte, alimentação), possibilidade de ter múltiplos clientes simultaneamente, construção de patrimônio empresarial, e potencial de crescimento escalável. Para empresas no Simples Nacional, a carga tributária pode ser inferior a 10% do faturamento.' },
      { title: 'Custos Ocultos do PJ que Você Precisa Conhecer', content: 'Ao optar pelo PJ, é importante considerar custos que não existem na CLT: contabilidade mensal (R$ 100-500/mês para ME), emissão de notas fiscais, abertura e manutenção da empresa, taxas de alvará e licenças, ausência de 13º salário (reserve mensalmente 8,33% do valor recebido), ausência de férias remuneradas (reserve 8,33% + 1/3 = 11,11%), ausência de FGTS, ausência de seguro-desemprego, e necessidade de plano de saúde privado.' },
      { title: 'Como Calcular o Valor PJ Equivalente ao CLT', content: 'Para saber quanto cobrar como PJ para equivaler a um salário CLT, multiplique o salário CLT desejado por aproximadamente 1,4 a 1,7. Exemplo: salário CLT de R$ 5.000,00 × 1,5 = R$ 7.500,00 como PJ. Esta margem cobre: INSS patronal (~20% sobre salário), FGTS (8%), 13º (8,33%), férias + 1/3 (11,11%), multa FGTS (3,2%), seguro-desemprego (~2%), vale-transporte, aviso prévio, e benefícios como plano de saúde. Use nossa calculadora CLT vs PJ para fazer essa simulação personalizada.' },
      { title: 'Aspectos Legais e Riscos do PJ', content: 'O PJ deve ser uma relação genuína de prestação de serviços entre empresas. Se a relação tiver características de vínculo empregatício (subordinação, pessoalidade, habitualidade, onerosidade), a Justiça do Trabalho pode reconhecer o vínculo CLT, gerando cobrança retroativa de todos os encargos trabalhistas. Para evitar o reconhecimento de vínculo, o profissional PJ deve ter autonomia, não ter subordinação direta, poder substituir-se por outro profissional, e prestar serviços para múltiplos clientes.' },
      { title: 'Qual Regime Escolher: Guia de Decisão', content: 'Escolha CLT se você valoriza estabilidade e segurança, está no início da carreira, prefere benefícios garantidos, não quer se preocupar com gestão fiscal, trabalha em regime de dedicação exclusiva, ou atua em área com mercado de trabalho aquecido para CLT. Escolha PJ se você tem experiência e network estabelecido, busca maior rentabilidade, tem perfil empreendedor, trabalha em área com alta demanda por projetos, possui múltiplos clientes, ou já tem reserva financeira para períodos sem contrato.' },
    ],
  },
  'guia-fgts': {
    sections: [
      { title: 'O que é o FGTS e Como Funciona?', content: 'O Fundo de Garantia do Tempo de Serviço (FGTS) foi criado pela Lei 5.107/1966 com o objetivo de proteger o trabalhador demitido sem justa causa. Atualmente regido pela Lei 8.036/1990, o FGTS funciona como uma poupança forçada em nome do trabalhador, administrada pela Caixa Econômica Federal. Mensalmente, o empregador deposita o equivalente a 8% do salário bruto do funcionário em uma conta vinculada ao FGTS. Esse depósito é obrigatório e não pode ser descontado do salário do empregado.' },
      { title: 'Depósitos Mensais: Quanto e Quando São Feitos', content: 'O empregador deve depositar 8% do salário bruto do funcionário até o dia 20 de cada mês. Se o dia 20 cair em feriado ou final de semana, o depósito deve ser antecipado. Além dos depósitos mensais sobre o salário, o empregador também deposita 8% sobre o valor do 13º salário. O não recolhimento do FGTS no prazo gera multa de 5% no primeiro mês e 10% nos meses seguintes, além de juros de mora. O saldo do FGTS é corrigido pela Taxa Referencial (TR) acrescida de juros de 3% ao ano.' },
      { title: 'Quando o Trabalhador Pode Sacar o FGTS?', content: 'As principais hipóteses de saque do FGTS são: demissão sem justa causa (saldo total), rescisão por acordo (80% do saldo), aposentadoria (saldo total), compra da casa própria dentro do SFH (saldo total), amortização ou liquidação de financiamento habitacional, doenças graves do trabalhador ou dependentes (câncer, HIV, doenças cardiovasculares), calamidade pública reconhecida pelo governo, falecimento do trabalhador (saque pelos dependentes), saque-aniversário (parcial anual), e saque de contas inativas do FGTS por necessidade pessoal (programas especiais do governo).' },
      { title: 'Multa de 40% do FGTS: Como Funciona', content: 'Em caso de dispensa sem justa causa, o empregador deve pagar multa de 40% sobre todo o saldo do FGTS, incluindo os depósitos sobre o 13º salário. Essa multa é paga via GRRF (Guia de Recolhimento Rescisório do FGTS) e creditada na conta do FGTS do trabalhador. Na rescisão por acordo (criada pela Reforma Trabalhista de 2017), a multa é de 20%. A multa é paga integralmente pelo empregador e não é descontada do salário do trabalhador. Em caso de pedido de demissão ou dispensa por justa causa, a multa não é devida.' },
      { title: 'Saque-Aniversário: Vale a Pena?', content: 'O saque-aniversário permite ao trabalhador retirar anualmente uma parte do saldo do FGTS no mês do seu aniversário. Os percentuais variam conforme o saldo: até R$ 500,00 (50%), de R$ 500,01 a R$ 1.000,00 (40%), de R$ 1.000,01 a R$ 15.000,00 (30% + parcela fixa), de R$ 15.000,01 a R$ 20.000,00 (15% + parcela fixa), acima de R$ 20.000,00 (5% + parcela fixa). Ao optar pelo saque-aniversário, o trabalhador PERDE o direito ao saque total do FGTS em caso de demissão sem justa causa, podendo sacar apenas a multa de 40% paga pelo empregador.' },
      { title: 'FGTS na Compra da Casa Própria', content: 'O FGTS pode ser utilizado para compra da casa própria dentro das regras do SFH (Sistema Financeiro de Habitação). É permitido usar o saldo do FGTS para dar entrada no imóvel, amortizar o saldo devedor, liquidar o financiamento ou pagar parte das prestações. Os requisitos incluem: ser optante do FGTS há pelo menos 3 anos, não ser proprietário de outro imóvel no mesmo município, não ter usado o FGTS para imóvel nos últimos 3 anos, e o imóvel deve estar dentro do valor máximo do SFH (R$ 1,5 milhão em 2024).' },
      { title: 'Como Consultar seu FGTS', content: 'O saldo do FGTS pode ser consultado de várias formas: pelo aplicativo FGTS (disponível gratuitamente para Android e iOS), pelo site da Caixa Econômica Federal (fgts.caixa.gov.br), nas agências da Caixa com documento de identificação e número do PIS/PASEP, pelo internet banking da Caixa, e pelo SMS informativo. O extrato do FGTS mostra todos os depósitos realizados mês a mês, o saldo atual, a data do último depósito e a rentabilidade acumulada.' },
      { title: 'FGTS e Aposentadoria: Como Sacar', content: 'Ao se aposentar, o trabalhador tem direito de sacar todo o saldo do FGTS. Para isso, é necessário apresentar a carta de concessão da aposentadoria emitida pelo INSS. O saque pode ser feito nas agências da Caixa Econômica Federal, mediante apresentação de documentos pessoais e da carta de aposentadoria. O saque do FGTS na aposentadoria não impede que o trabalhador continue contribuindo para o FGTS se continuar trabalhando.' },
      { title: 'Rendimento do FGTS: Vale a Pena Deixar o Dinheiro Lá?', content: 'O FGTS rende TR + 3% ao ano. Historicamente, esse rendimento é inferior à poupança (que rende 0,5% ao mês, aproximadamente 6,17% ao ano) e muito inferior a investimentos como CDBs (110% do CDI ≈ 12% ao ano), Tesouro Direto Selic (≈ 11,25% ao ano) ou fundos de renda fixa. Por exemplo, R$ 10.000,00 em 5 anos no FGTS rendem aproximadamente R$ 11.600,00; na poupança renderiam R$ 13.400,00; em um CDB renderiam R$ 16.100,00. Por isso, especialistas recomendam sacar o FGTS nas situações permitidas e investir em opções mais rentáveis.' },
      { title: 'FGTS Trabalhista: Direitos em Caso de Sonegação', content: 'Se o empregador não depositar o FGTS regularmente, o trabalhador pode: exigir os depósitos atrasados via reclamação trabalhista na Justiça do Trabalho, solicitar a rescisão indireta do contrato (por descumprimento de obrigação legal), e denunciar a empresa ao Ministério Público do Trabalho. A Súmula 362 do TST estabelece que o prazo prescricional para cobrança do FGTS é de 30 anos, exceto para trabalhadores que ingressaram após a Reforma Trabalhista.' },
    ],
  },
  'passo-rescisao': {
    sections: [
      { title: 'O que é a Rescisão Trabalhista?', content: 'A rescisão trabalhista é o término do contrato de trabalho entre empregado e empregador, momento em que o trabalhador tem direito a receber as verbas rescisórias correspondentes ao tempo trabalhado e ao tipo de desligamento. O processo envolve desde a preparação dos documentos até o pagamento final das verbas, que deve ocorrer em até 10 dias corridos após o término do contrato. Entender cada etapa ajuda o trabalhador a conferir se todos os seus direitos estão sendo respeitados.' },
      { title: 'Tipos de Rescisão Contratual', content: 'Existem seis tipos principais de rescisão: 1) Dispensa sem justa causa: empregador dispensa o funcionário sem motivo grave; garante todas as verbas + multa de 40% FGTS + seguro-desemprego. 2) Dispensa por justa causa: empregado comete falta grave; perde aviso prévio, multa FGTS e seguro-desemprego. 3) Pedido de demissão: empregado pede para sair; aviso prévio pode ser descontado. 4) Rescisão indireta: empregador comete falta grave; equivale à dispensa sem justa causa. 5) Rescisão por acordo: Lei 13.467/2017; multa FGTS de 20%, saque de 80%, sem seguro-desemprego. 6) Término de contrato por prazo determinado ou temporário.' },
      { title: 'Documentação Necessária para a Rescisão', content: 'Para realizar a rescisão, são necessários os seguintes documentos: Carteira de Trabalho e Previdência Social (CTPS) com as devidas anotações atualizadas, Termo de Rescisão do Contrato de Trabalho (TRCT) em duas vias, Guias de Seguro-Desemprego (requerimento), extrato para saque do FGTS, exame médico demissional (obrigatório), Programa de Desligamento (PDV se aplicável), e comprovantes de pagamento das verbas rescisórias. Para a homologação (quando exigida), são necessários também o contrato de trabalho, holerites dos últimos meses e convenção coletiva da categoria.' },
      { title: 'Cálculo das Verbas Rescisórias Passo a Passo', content: 'As verbas rescisórias incluem: 1) Saldo de salário: dias trabalhados no mês da rescisão ÷ 30 × salário. 2) Aviso prévio: 30 dias + 3 dias por ano adicional (máx. 90 dias). 3) Férias vencidas + 1/3, se houver período aquisitivo completo. 4) Férias proporcionais + 1/3: (salário ÷ 12) × meses trabalhados no período aquisitivo + 1/3. 5) 13º proporcional: (salário ÷ 12) × meses trabalhados no ano. 6) Multa FGTS: 40% do saldo (dispensa sem justa causa) ou 20% (acordo). 7) Saque do FGTS: saldo total ou 80% (acordo).' },
      { title: 'Homologação da Rescisão: Quando é Necessária?', content: 'A homologação da rescisão no sindicato, antes obrigatória para contratos com mais de 1 ano, foi alterada pela Reforma Trabalhista de 2017. Atualmente, a assistência do sindicato é necessária quando o contrato tem mais de 1 ano e o empregado não tem capacidade financeira comprovada para contratar advogado. O empregador também pode optar pela assistência do Ministério do Trabalho, do sindicato ou do Ministério Público do Trabalho. A homologação é uma proteção para ambas as partes, garantindo que os direitos foram pagos corretamente.' },
      { title: 'Prazos Legais para Pagamento', content: 'O prazo para pagamento das verbas rescisórias é de até 10 dias corridos contados da data do término do contrato de trabalho (artigo 477 da CLT). Se o aviso prévio for indenizado, o prazo conta da data da comunicação da dispensa. Se for trabalhado, conta do último dia trabalhado. O atraso no pagamento gera multa de um salário do empregado, além de correção monetária e juros de mora de 1% ao mês. O pagamento deve ser feito em dinheiro, depósito bancário ou cheque administrativo.' },
      { title: 'Direitos em Caso de Atraso no Pagamento', content: 'Se o empregador não pagar as verbas rescisórias no prazo de 10 dias, o trabalhador pode: exigir o pagamento com multa de 1 salário (artigo 477, §8º da CLT), ingressar com reclamação trabalhista na Justiça do Trabalho, solicitar os valores via ação de consignação em pagamento, e denunciar a empresa ao Ministério do Trabalho. O trabalhador também pode requerer a rescisão indireta do contrato se ainda estiver trabalhando. A multa por atraso é devida independentemente de o empregador ter ou não culpa pelo atraso.' },
      { title: 'Verbas que Não São Devidas na Rescisão', content: 'É importante saber o que NÃO é devido na rescisão para evitar cobranças indevidas: Adicional de periculosidade ou insalubridade não são devidos se o trabalhador nunca os recebeu, PLR se não houver acordo ou a empresa não tiver lucro, participação nos lucros se não prevista, horas extras se não foram trabalhadas, vale-transporte de dias não trabalhados (se não utilizado), e plano de saúde após o período de manutenção (30 a 90 dias). O seguro-desemprego é um benefício do governo, não pago pela empresa.' },
      { title: 'Alterações da Reforma Trabalhista na Rescisão', content: 'A Reforma Trabalhista de 2017 (Lei 13.467/2017) trouxe mudanças importantes: criação da rescisão por acordo (multa FGTS de 20% e saque de 80%), fim da obrigatoriedade da homologação sindical para contratos acima de 1 ano, parcelamento das férias em até 3 períodos, e possibilidade de demissão por acordo sem necessidade de assistência sindical. Também foram alteradas as regras para o aviso prévio, que agora pode ser descontado em caso de pedido de demissão com menos de 1 ano de trabalho.' },
      { title: 'Dicas para Conferir sua Rescisão', content: 'Ao receber o TRCT, verifique: se seu nome e dados estão corretos, se a data de admissão e demissão estão certas, se o tipo de rescisão está correto, se o saldo de salário corresponde aos dias trabalhados, se as férias estão proporcionais ao período aquisitivo, se o 13º está proporcional aos meses do ano, se o aviso prévio está de acordo com o tempo de serviço, se a multa do FGTS está correta (40% ou 20%), e se o valor total está de acordo com as verbas devidas. Em caso de dúvida, não assine o documento e procure o sindicato ou um advogado trabalhista.' },
    ],
  },
};

export default function GuiaPage() {
  const { guideId } = useParams<{ guideId: string }>();
  const guide = guides.find(g => g.id === guideId);
  const content = guideContent[guideId || ''];

  if (!guide || !content) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16 text-center">
        <BookOpen className="w-16 h-16 mx-auto text-gray-300 mb-4" />
        <h1 className="text-2xl font-bold text-gray-900 mb-2">Guia não encontrado</h1>
        <p className="text-gray-500 mb-6">O guia que você procura não foi encontrado.</p>
        <Link to="/guias" className="btn-primary">Ver Todos os Guias</Link>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8">
      <Link to="/guias" className="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-primary-600 mb-6 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Voltar para Guias
      </Link>

      <article>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{__html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": guide.title,
            "description": guide.description,
          })}}
        />

        <div className="flex items-center gap-3 mb-4">
          <BookOpen className="w-6 h-6 text-amber-500" />
          <span className="text-xs font-medium text-amber-600 bg-amber-50 px-2 py-0.5 rounded-full">Guia Trabalhista</span>
        </div>
        <h1 className="text-3xl font-bold text-gray-900 mb-6">{guide.title}</h1>
        <p className="text-lg text-gray-600 mb-8">{guide.description}</p>

        <AdSensePlaceholder format="horizontal" className="mb-8" />

        <div className="space-y-8">
          {content.sections.map((section, i) => (
            <div key={i}>
              <h2 className="text-xl font-bold text-gray-900 mb-3">{section.title}</h2>
              <p className="text-gray-600 leading-relaxed">{section.content}</p>
            </div>
          ))}
        </div>

        <AdSensePlaceholder format="horizontal" className="mt-8" />

        <div className="mt-8 bg-primary-50 rounded-xl p-6">
          <h3 className="font-semibold text-gray-900 mb-2">Precisa calcular seus direitos?</h3>
          <p className="text-sm text-gray-600 mb-4">Use nossas calculadoras gratuitas para simular os valores exatos.</p>
          <Link to="/ferramentas" className="btn-primary inline-flex items-center gap-2">Ver Calculadoras</Link>
        </div>
      </article>
    </div>
  );
}
