import type { CLTDireito } from './types';

export const cltCategories = [
  { id: 'direitos-fundamentais', name: 'Direitos Fundamentais' },
  { id: 'jornada-trabalho', name: 'Jornada de Trabalho' },
  { id: 'remuneracao', name: 'Remuneração' },
  { id: 'contrato', name: 'Contrato de Trabalho' },
  { id: 'rescisao', name: 'Rescisão Contratual' },
  { id: 'adicionais', name: 'Adicionais Salariais' },
  { id: 'licencas', name: 'Licenças e Afastamentos' },
  { id: 'seguranca', name: 'Segurança e Saúde' },
  { id: 'mulher', name: 'Proteção à Mulher Trabalhadora' },
  { id: 'aprendiz', name: 'Menor Aprendiz' },
];

export const cltDireitos: CLTDireito[] = [
  {
    id: 'salario-minimo',
    slug: 'salario-minimo',
    title: 'Salário Mínimo: Direito Fundamental do Trabalhador',
    description: 'O salário mínimo é o menor valor que pode ser pago a um trabalhador brasileiro, fixado em lei. Em 2025 o valor é R$ 1.518,00.',
    content: 'O salário mínimo constitui direito social fundamental previsto no artigo 7º, inciso IV da Constituição Federal. O artigo 76 da CLT regulamenta que o salário mínimo é a contraprestação mínima devida ao trabalhador. Em 2025 o salário mínimo foi reajustado para R$ 1.518,00. O salário mínimo serve como base para o cálculo do seguro-desemprego, abono salarial PIS/PASEP, benefícios do INSS e adicional de insalubridade.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7º, IV - CF/88',
    cltArticles: 'Arts. 76 a 81 da CLT',
    icon: 'DollarSign',
    tags: ['salário mínimo', 'piso salarial', 'remuneração mínima', 'CF artigo 7º'],
    faq: [
      { question: 'Qual o valor do salário mínimo em 2025?', answer: 'O salário mínimo em 2025 é de R$ 1.518,00 conforme decreto federal.' },
      { question: 'O salário mínimo serve de base para quais benefícios?', answer: 'Seguro-desemprego, abono salarial PIS/PASEP, benefícios do INSS e adicional de insalubridade.' },
    ],
    praticas: ['Verifique se seu salário é igual ou superior ao salário mínimo vigente de R$ 1.518,00 para jornada integral', 'Consulte a convenção coletiva da sua categoria para verificar se existe piso salarial superior ao mínimo'],
    metaDescription: 'Salário mínimo 2025: R$ 1.518,00. Direito fundamental previsto no artigo 7º, IV da CF/88 e artigos 76-81 da CLT.',
  },
  {
    id: 'jornada-trabalho',
    slug: 'jornada-de-trabalho-clt',
    title: 'Jornada de Trabalho: Limites Legais',
    description: 'A jornada padrão é de 8 horas diárias e 44 horas semanais. Conheça os limites e exceções.',
    content: 'A jornada de trabalho é regulada pelo artigo 7º, XIII da CF e artigos 58 a 75 da CLT. O limite é de 8 horas diárias e 44 horas semanais, com até 2 horas extras por dia. Existem jornadas especiais para bancários (6h), telemarketing (6h) e jornalistas (5h). A Reforma Trabalhista de 2017 autorizou a jornada 12x36 e o banco de horas por acordo individual.',
    category: 'Jornada de Trabalho',
    cfArticle: 'Art. 7º, XIII - CF/88',
    cltArticles: 'Arts. 58 a 75 da CLT',
    icon: 'Clock',
    tags: ['jornada de trabalho', '44 horas semanais', 'carga horária', 'CLT jornada'],
    faq: [
      { question: 'Qual a jornada máxima de trabalho?', answer: '8 horas diárias e 44 horas semanais. Com horas extras, o limite é de 10 horas diárias.' },
      { question: 'O que é a jornada 12x36?', answer: 'Regime de 12 horas de trabalho por 36 de descanso, autorizado por acordo individual.' },
    ],
    praticas: ['Sua jornada padrão é de no máximo 8h diárias e 44h semanais', 'Horas extras limitadas a 2h por dia'],
    metaDescription: 'Jornada de trabalho CLT: 8 horas diárias, 44 horas semanais. Art. 7º, XIII CF/88 e arts. 58-75 CLT.',
  },
  {
    id: 'horas-extras',
    slug: 'horas-extras-direito-trabalhista',
    title: 'Horas Extras: Cálculo e Direitos',
    description: 'Horas extras são pagas com adicional mínimo de 50% sobre a hora normal em dias úteis e 100% em domingos e feriados.',
    content: 'O direito a horas extras está previsto no artigo 7º, XVI da CF e artigo 59 da CLT. O adicional mínimo é 50% em dias úteis e 100% em domingos e feriados. O limite é de 2 horas extras por dia. O cálculo usa o divisor 220 para jornada de 44h semanais. Horas extras habituais geram reflexos no DSR, férias, 13º e FGTS conforme OJ 394 da SDI-1 do TST.',
    category: 'Jornada de Trabalho',
    cfArticle: 'Art. 7º, XVI - CF/88',
    cltArticles: 'Art. 59 da CLT',
    icon: 'Clock',
    tags: ['horas extras', 'adicional 50%', 'adicional 100%', 'cálculo hora extra'],
    faq: [
      { question: 'Qual o adicional mínimo para horas extras?', answer: '50% em dias úteis e 100% em domingos e feriados.' },
      { question: 'Horas extras geram reflexo em outras verbas?', answer: 'Sim. Integram DSR, férias, 13º e FGTS.' },
    ],
    praticas: ['Calcule a hora normal dividindo o salário por 220', 'Hora extra em dia útil: multiplique por 1,5'],
    metaDescription: 'Horas extras CLT: adicional de 50% e 100%, cálculo e reflexos. Art. 59 CLT e Art. 7º, XVI CF/88.',
  },
  {
    id: 'ferias-direito',
    slug: 'ferias-direito-trabalhador',
    title: 'Férias: 30 Dias + 1/3 Constitucional',
    description: 'Após 12 meses de trabalho o empregado tem direito a 30 dias de férias com adicional de 1/3 do salário.',
    content: 'As férias são garantidas pelo artigo 7º, XVII da CF e artigos 129 a 153 da CLT. São 30 dias após 12 meses de trabalho (período aquisitivo). O valor inclui 1/3 constitucional. As férias podem ser parceladas em até 3 períodos. O abono pecuniário permite vender 10 dias de férias. Faltas não justificadas reduzem os dias de férias conforme artigo 130 da CLT.',
    category: 'Remuneração',
    cfArticle: 'Art. 7º, XVII - CF/88',
    cltArticles: 'Arts. 129 a 153 da CLT',
    icon: 'Umbrella',
    tags: ['férias', 'terço constitucional', 'abono pecuniário', 'férias em dobro'],
    faq: [
      { question: 'Quando as férias são pagas em dobro?', answer: 'Quando o empregador não concede as férias dentro do período concessivo de 12 meses.' },
      { question: 'Como funciona o abono pecuniário?', answer: 'Permite converter 1/3 das férias (10 dias) em dinheiro, solicitado até 15 dias antes do período aquisitivo.' },
    ],
    praticas: ['Após 12 meses você tem direito a 30 dias de férias + 1/3', 'Você pode vender 10 dias de férias (abono pecuniário)'],
    metaDescription: 'Férias trabalhistas: 30 dias + 1/3 constitucional. Arts. 129-153 CLT e Art. 7º, XVII CF/88.',
  },
  {
    id: 'fgts',
    slug: 'fgts-direitos-trabalhador',
    title: 'FGTS: Fundo de Garantia',
    description: 'O empregador deposita 8% do salário mensalmente. Saiba como funciona o saque e a multa de 40%.',
    content: 'O FGTS é regido pela Lei 8.036/1990 e garantido pelo artigo 7º, III da CF. O empregador deposita 8% do salário em conta na Caixa Econômica Federal. Em caso de dispensa sem justa causa, o trabalhador saca o saldo total mais multa de 40% paga pelo empregador. Na rescisão por acordo a multa é de 20%. O FGTS também pode ser sacado para casa própria, aposentadoria e doenças graves.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7º, III - CF/88',
    cltArticles: 'Lei 8.036/1990',
    icon: 'PiggyBank',
    tags: ['FGTS', 'fundo de garantia', 'multa FGTS', 'saque FGTS'],
    faq: [
      { question: 'Qual o percentual de depósito do FGTS?', answer: '8% do salário bruto mensalmente, depositado pelo empregador até o dia 20.' },
      { question: 'Quanto é a multa do FGTS na demissão?', answer: '40% sobre o saldo total na dispensa sem justa causa; 20% na rescisão por acordo.' },
    ],
    praticas: ['Consulte seu FGTS pelo aplicativo da Caixa', 'Em caso de demissão sem justa causa, saque saldo total + multa de 40%'],
    metaDescription: 'FGTS: depósito de 8%, multa de 40%, saque-aniversário. Lei 8.036/1990 e Art. 7º, III CF/88.',
  },
  {
    id: 'adicional-noturno',
    slug: 'adicional-noturno-regras-clt',
    title: 'Adicional Noturno: 20% + Hora Reduzida',
    description: 'Adicional de 20% sobre a hora normal para trabalho entre 22h e 5h, com redução da hora para 52min30s.',
    content: 'O adicional noturno é regulado pelo artigo 73 da CLT e artigo 7º, IX da CF. O período noturno é das 22h às 5h. O adicional mínimo é 20% sobre a hora normal. A hora noturna é de 52 minutos e 30 segundos. O adicional integra o salário para férias, 13º e FGTS. A Súmula 60 do TST garante o adicional na prorrogação além das 5h.',
    category: 'Adicionais Salariais',
    cfArticle: 'Art. 7º, IX - CF/88',
    cltArticles: 'Art. 73 da CLT',
    icon: 'Moon',
    tags: ['adicional noturno', 'hora noturna', 'redução hora noturna'],
    faq: [
      { question: 'Qual o percentual do adicional noturno?', answer: '20% sobre a hora normal para trabalhadores urbanos.' },
      { question: 'Como funciona a redução da hora noturna?', answer: 'Cada hora noturna tem 52 minutos e 30 segundos. 7 horas trabalhadas são pagas como 8.' },
    ],
    praticas: ['O adicional noturno mínimo é de 20% sobre a hora normal', 'Cada hora noturna equivale a 52 minutos e meio'],
    metaDescription: 'Adicional noturno CLT: 20% sobre a hora normal, hora reduzida para 52min30s. Art. 73 CLT.',
  },
  {
    id: 'insalubridade',
    slug: 'adicional-de-insalubridade',
    title: 'Adicional de Insalubridade: 10% a 40%',
    description: 'Adicional devido a expostos a agentes nocivos: 10% (mínimo), 20% (médio) ou 40% (máximo) do salário mínimo.',
    content: 'O adicional de insalubridade é regulado pelo artigo 192 da CLT e NR-15. Os graus são: mínimo (10%), médio (20%) e máximo (40%) do salário mínimo. A caracterização exige perícia técnica. Agentes insalubres incluem ruído, calor, agentes químicos e biológicos. Com salário mínimo de R$ 1.518,00: mínimo R$ 151,80, médio R$ 303,60, máximo R$ 607,20.',
    category: 'Adicionais Salariais',
    cfArticle: 'Art. 7º, XXIII - CF/88',
    cltArticles: 'Arts. 189 a 197 da CLT / NR-15',
    icon: 'AlertTriangle',
    tags: ['insalubridade', 'adicional insalubridade', 'NR-15', 'agentes nocivos'],
    faq: [
      { question: 'Quais os percentuais do adicional de insalubridade?', answer: '10% (mínimo), 20% (médio) e 40% (máximo) do salário mínimo.' },
      { question: 'O uso de EPIs elimina o adicional?', answer: 'Sim, se os EPIs neutralizarem completamente a insalubridade com fiscalização do uso.' },
    ],
    praticas: ['O adicional varia de 10% a 40% do salário mínimo conforme o grau', 'A caracterização exige perícia técnica'],
    metaDescription: 'Adicional de insalubridade: 10%, 20% ou 40% do salário mínimo. Art. 192 CLT e NR-15.',
  },
  {
    id: 'periculosidade',
    slug: 'adicional-de-periculosidade',
    title: 'Adicional de Periculosidade: 30% do Salário Base',
    description: 'Adicional de 30% sobre o salário base para atividades perigosas como inflamáveis, explosivos e energia elétrica.',
    content: 'O adicional de periculosidade é regulado pelo artigo 193 da CLT e NR-16. É de 30% sobre o salário base. Atividades perigosas incluem inflamáveis, explosivos, energia elétrica e vigilância. A caracterização exige perícia técnica. Pode ser acumulado com insalubridade se houver previsão em acordo coletivo.',
    category: 'Adicionais Salariais',
    cfArticle: 'Art. 7º, XXIII - CF/88',
    cltArticles: 'Art. 193 da CLT / NR-16',
    icon: 'Zap',
    tags: ['periculosidade', 'adicional periculosidade', 'atividade perigosa', 'NR-16'],
    faq: [
      { question: 'Qual o valor do adicional de periculosidade?', answer: '30% sobre o salário base do empregado.' },
      { question: 'Pode acumular periculosidade e insalubridade?', answer: 'Sim, desde a Reforma Trabalhista de 2017, com previsão em acordo coletivo.' },
    ],
    praticas: ['O adicional é de 30% sobre o salário base', 'Eletricistas, frentistas, vigilantes têm direito ao adicional'],
    metaDescription: 'Adicional de periculosidade: 30% do salário base. NR-16, Art. 193 CLT.',
  },
  {
    id: 'aviso-previo',
    slug: 'aviso-previo-direito-trabalhista',
    title: 'Aviso Prévio: 30 a 90 Dias',
    description: 'Aviso prévio de 30 a 90 dias conforme o tempo de serviço, nas modalidades trabalhado ou indenizado.',
    content: 'O aviso prévio está previsto no artigo 7º, XXI da CF e Lei 12.506/2011. São 30 dias para contratos de até 1 ano, mais 3 dias por ano adicional, limitado a 90 dias. Pode ser trabalhado (com redução de 2h diárias) ou indenizado. O período integra o contrato para todos os efeitos legais.',
    category: 'Rescisão Contratual',
    cfArticle: 'Art. 7º, XXI - CF/88',
    cltArticles: 'Arts. 487 a 491 da CLT / Lei 12.506/2011',
    icon: 'Bell',
    tags: ['aviso prévio', 'aviso prévio proporcional', 'aviso indenizado'],
    faq: [
      { question: 'Como calcular o aviso prévio proporcional?', answer: '30 dias + 3 dias por ano adicional, máximo 90 dias.' },
      { question: 'Quais os direitos durante o aviso prévio?', answer: 'Redução de 2h diárias ou 7 dias de folga, manutenção dos benefícios.' },
    ],
    praticas: ['Aviso prévio mínimo de 30 dias até 90 dias conforme tempo de serviço', 'No aviso trabalhado você tem direito a sair 2h mais cedo'],
    metaDescription: 'Aviso prévio: 30 a 90 dias. Lei 12.506/2011 e Art. 7º, XXI CF/88.',
  },
  {
    id: 'seguro-desemprego',
    slug: 'seguro-desemprego-direito',
    title: 'Seguro-Desemprego',
    description: 'Benefício de 3 a 5 parcelas ao trabalhador dispensado sem justa causa.',
    content: 'O seguro-desemprego é garantido pelo artigo 7º, II da CF e Lei 7.998/1990. Oferece 3 a 5 parcelas conforme tempo trabalhado. O valor é calculado pela média dos 3 últimos salários. Solicitação pelo Gov.br do 7º ao 120º dia após a dispensa.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7º, II - CF/88',
    cltArticles: 'Lei 7.998/1990',
    icon: 'Briefcase',
    tags: ['seguro desemprego', 'parcelas', 'cálculo seguro desemprego'],
    faq: [
      { question: 'Quantas parcelas do seguro-desemprego?', answer: '3 a 5 parcelas conforme tempo trabalhado e número de solicitações.' },
      { question: 'Qual o prazo para solicitar?', answer: 'Do 7º ao 120º dia após a dispensa, pelo Gov.br.' },
    ],
    praticas: ['Solicite do 7º ao 120º dia após a dispensa', 'Faça a solicitação online pelo Gov.br'],
    metaDescription: 'Seguro-desemprego: 3 a 5 parcelas. Art. 7º, II CF/88 e Lei 7.998/1990.',
  },
  {
    id: 'estabilidade-provisoria',
    slug: 'estabilidade-provisoria-emprego',
    title: 'Estabilidade Provisória',
    description: 'Gestante, CIPA, acidentado e dirigente sindical têm estabilidade no emprego.',
    content: 'A estabilidade provisória impede a dispensa sem justa causa durante período determinado. Gestante: desde a confirmação da gravidez até 5 meses após o parto (ADCT art. 10, II, b). Membro da CIPA: da candidatura a 1 ano após o mandato. Acidentado: 12 meses após retorno (art. 118 Lei 8.213/91). Dirigente sindical: durante o mandato.',
    category: 'Contrato de Trabalho',
    cfArticle: 'Art. 7º, I - CF/88',
    cltArticles: 'Arts. 165, 543 CLT / ADCT Art. 10, II, b',
    icon: 'Shield',
    tags: ['estabilidade', 'gestante', 'CIPA', 'acidente de trabalho'],
    faq: [
      { question: 'Quem tem direito à estabilidade?', answer: 'Gestante, CIPA, acidentado, dirigente sindical e representante de empregados.' },
      { question: 'A gestante tem estabilidade em contrato temporário?', answer: 'Sim, conforme Súmula 244 do TST.' },
    ],
    praticas: ['Gestante: estabilidade da gravidez a 5 meses após o parto', 'Membro da CIPA: da candidatura a 1 ano após o mandato'],
    metaDescription: 'Estabilidade provisória: gestante, CIPA, acidentado, dirigente sindical. CLT e ADCT.',
  },
  {
    id: 'rescisao-contratual',
    slug: 'rescisao-contratual-tipos-verbas',
    title: 'Rescisão Contratual',
    description: 'Tipos de desligamento e verbas devidas em cada caso: sem justa causa, justa causa, pedido de demissão e acordo.',
    content: 'A rescisão contratual é regulada pelos artigos 477 a 486 da CLT. Na dispensa sem justa causa: saldo de salário, aviso prévio, férias + 1/3, 13º, multa de 40% do FGTS e seguro-desemprego. Na justa causa: apenas saldo de salário e férias. No pedido de demissão: saldo, férias, 13º e saque do FGTS. No acordo: multa de 20% do FGTS e saque de 80%, sem seguro-desemprego.',
    category: 'Rescisão Contratual',
    cfArticle: 'Art. 7º, I e XXI - CF/88',
    cltArticles: 'Arts. 477 a 486 da CLT',
    icon: 'FileText',
    tags: ['rescisão', 'dispensa', 'justa causa', 'pedido demissão'],
    faq: [
      { question: 'Quais os direitos na dispensa sem justa causa?', answer: 'Saldo de salário, aviso prévio, férias + 1/3, 13º, multa de 40% do FGTS e seguro-desemprego.' },
      { question: 'Como funciona a rescisão por acordo?', answer: 'Multa de 20% do FGTS, saque de 80%, sem seguro-desemprego.' },
    ],
    praticas: ['Na dispensa sem justa causa você tem direito a multa de 40% do FGTS', 'Prazo de pagamento: 10 dias corridos após o término do contrato'],
    metaDescription: 'Rescisão contratual: tipos de desligamento e verbas devidas. Arts. 477-486 CLT.',
  },
  {
    id: 'intervalo-intrajornada',
    slug: 'intervalo-intrajornada-clt',
    title: 'Intervalo Intrajornada',
    description: 'Intervalo mínimo de 1 hora para jornadas acima de 6 horas. A não concessão gera pagamento como hora extra.',
    content: 'O intervalo intrajornada é regulado pelo artigo 71 da CLT e Súmula 437 do TST. Para jornadas acima de 6h: mínimo 1h. Para 4h a 6h: 15 minutos. A não concessão gera pagamento como hora extra com adicional de 50%. O STF (Tema 1046) validou a redução por acordo coletivo.',
    category: 'Jornada de Trabalho',
    cfArticle: 'Art. 7º, XIII - CF/88',
    cltArticles: 'Arts. 71 da CLT / Súmula 437 do TST',
    icon: 'Coffee',
    tags: ['intervalo intrajornada', 'almoço', 'descanso', 'Súmula 437 TST'],
    faq: [
      { question: 'Qual a duração do intervalo?', answer: '1h para jornadas acima de 6h, 15 min para 4h a 6h.' },
      { question: 'O que acontece se o intervalo não for concedido?', answer: 'Pagamento como hora extra com adicional de 50%.' },
    ],
    praticas: ['Para jornadas acima de 6h você tem direito a no mínimo 1h de intervalo', 'O intervalo não é computado na jornada de trabalho'],
    metaDescription: 'Intervalo intrajornada CLT: 1h para jornadas acima de 6h. Súmula 437 do TST. Art. 71 CLT.',
  },
  {
    id: 'licenca-maternidade',
    slug: 'licenca-maternidade-direito',
    title: 'Licença-Maternidade: 120 Dias',
    description: '120 dias de licença com salário integral e estabilidade da gravidez a 5 meses após o parto.',
    content: 'A licença-maternidade é garantida pelo artigo 7º, XVIII da CF e artigos 391 a 400 da CLT. São 120 dias (180 dias no Programa Empresa Cidadã). A gestante tem estabilidade desde a confirmação da gravidez até 5 meses após o parto (Súmula 244 do TST). O salário-maternidade é pago pelo INSS.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7º, XVIII - CF/88',
    cltArticles: 'Arts. 391 a 400 da CLT',
    icon: 'Heart',
    tags: ['licença maternidade', 'gestante', 'estabilidade gestante'],
    faq: [
      { question: 'Quanto tempo dura a licença-maternidade?', answer: '120 dias (180 dias no Programa Empresa Cidadã).' },
      { question: 'A gestante tem estabilidade?', answer: 'Sim, da gravidez a 5 meses após o parto.' },
    ],
    praticas: ['Licença de 120 dias com salário integral', 'Estabilidade da gravidez a 5 meses após o parto'],
    metaDescription: 'Licença-maternidade: 120 dias com salário integral e estabilidade. Art. 7º, XVIII CF/88.',
  },
  {
    id: 'decimo-terceiro',
    slug: 'decimo-terceiro-salario',
    title: '13º Salário',
    description: 'Pago em duas parcelas: primeira até 30/11 sem descontos e segunda até 20/12 com INSS e IRRF.',
    content: 'O 13º salário é garantido pelo artigo 7º, VIII da CF e Leis 4.090/62 e 4.749/65. É pago em duas parcelas: primeira até 30/11 (sem descontos) e segunda até 20/12 (com INSS e IRRF). O valor é proporcional aos meses trabalhados. Horas extras habituais integram o cálculo (Súmula 45 do TST).',
    category: 'Remuneração',
    cfArticle: 'Art. 7º, VIII - CF/88',
    cltArticles: 'Lei 4.090/1962, Lei 4.749/1965',
    icon: 'Gift',
    tags: ['13º salário', 'gratificação natalina', 'décimo terceiro'],
    faq: [
      { question: 'Quando o 13º deve ser pago?', answer: '1ª parcela até 30/11, 2ª parcela até 20/12.' },
      { question: 'Quais descontos incidem?', answer: 'INSS e IRRF na segunda parcela. FGTS sobre o valor total.' },
    ],
    praticas: ['1ª parcela sem descontos até 30/11', '2ª parcela com INSS e IRRF até 20/12'],
    metaDescription: '13º salário: prazos e cálculo. Art. 7º, VIII CF/88, Leis 4.090/62 e 4.749/65.',
  },
  {
    id: 'prescricao-trabalhista',
    slug: 'prazo-prescricional-trabalhista',
    title: 'Prescrição Trabalhista',
    description: 'Prazo de 5 anos durante o contrato e 2 anos após a extinção para cobrar direitos na Justiça do Trabalho.',
    content: 'A prescrição trabalhista é regida pelo artigo 7º, XXIX da CF. Durante o contrato: 5 anos (prescrição quinquenal). Após a extinção: 2 anos para ajuizar a ação (prescrição bienal). FGTS tem prazo de 30 anos (contratos antigos) ou 5 anos (após Reforma de 2017). Dano moral em ricochete: 3 anos (Tema 126 TST).',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7º, XXIX - CF/88',
    cltArticles: 'Arts. 10 e 11 da CLT / Súmula 362 TST',
    icon: 'Calendar',
    tags: ['prescrição', 'prazo prescricional', 'Justiça do Trabalho'],
    faq: [
      { question: 'Qual o prazo para ajuizar ação após a demissão?', answer: '2 anos após o término do contrato.' },
      { question: 'Qual o prazo para cobrar FGTS?', answer: '30 anos (contratos antigos) ou 5 anos (após a Reforma de 2017).' },
    ],
    praticas: ['Durante o contrato: pode cobrar direitos dos últimos 5 anos', 'Após demissão: 2 anos para entrar com ação'],
    metaDescription: 'Prescrição trabalhista: 5 anos durante o contrato, 2 anos após demissão. Art. 7º, XXIX CF/88.',
  },
  {
    id: 'reforma-trabalhista',
    slug: 'reforma-trabalhista-lei-13467',
    title: 'Reforma Trabalhista Lei 13.467/2017',
    description: 'Principais mudanças: contribuição sindical facultativa, parcelamento de férias, rescisão por acordo e terceirização.',
    content: 'A Reforma Trabalhista (Lei 13.467/2017) alterou mais de 100 dispositivos da CLT. Principais mudanças: contribuição sindical facultativa, férias em até 3 períodos, rescisão por acordo (multa de 20% do FGTS), terceirização permitida para atividade-fim, contrato intermitente, jornada 12x36 por acordo individual e prevalência do negociado sobre o legislado.',
    category: 'Contrato de Trabalho',
    cfArticle: 'Art. 7º - CF/88',
    cltArticles: 'Lei 13.467/2017',
    icon: 'FileText',
    tags: ['reforma trabalhista', 'Lei 13.467', 'CLT 2017'],
    faq: [
      { question: 'A contribuição sindical ainda é obrigatória?', answer: 'Não. É facultativa desde a Reforma de 2017.' },
      { question: 'O que mudou na rescisão por acordo?', answer: 'Multa de 20% do FGTS, saque de 80%, sem seguro-desemprego.' },
    ],
    praticas: ['Contribuição sindical não é mais obrigatória', 'Férias podem ser parceladas em até 3 períodos'],
    metaDescription: 'Reforma Trabalhista Lei 13.467/2017: principais mudanças na CLT.',
  },
];
