import type { CLTDireito } from './types';

export const cltCategories = [
  { id: 'direitos-fundamentais', name: 'Direitos Fundamentais' },
  { id: 'jornada-trabalho', name: 'Jornada de Trabalho' },
  { id: 'remuneracao', name: 'Remuneração' },
  { id: 'contrato', name: 'Contrato de Trabalho' },
  { id: 'rescissao', name: 'Rescisão Contratual' },
  { id: 'adicionais', name: 'Adicionais Salariais' },
];

export const cltDireitos: CLTDireito[] = [
  {
    id: 'salario-minimo',
    slug: 'salario-minimo',
    title: 'Salário Mínimo: Direito Fundamental do Trabalhador',
    description: 'O salário mínimo é o menor valor que pode ser pago a um trabalhador brasileiro, fixado em lei nacional unificada. Em 2025 o valor é R$ 1.518,00.',
    content: 'O salário mínimo constitui direito social fundamental previsto no artigo 7º, IV da Constituição Federal de 1988. Os artigos 76 a 81 da CLT regulamentam o salário mínimo no âmbito trabalhista. O artigo 76 estabelece que o salário mínimo é a contraprestação mínima devida ao trabalhador.\n\nEm 2025 o salário mínimo foi reajustado para R$ 1.518,00. O reajuste considera a inflação medida pelo INPC mais o crescimento do PIB de dois anos anteriores.\n\nO salário mínimo serve como base para o cálculo do seguro-desemprego, abono salarial PIS/PASEP, benefícios do INSS e adicional de insalubridade.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7º, IV - CF/88',
    cltArticles: 'Arts. 76 a 81 da CLT',
    icon: 'DollarSign',
    tags: ['salario minimo', 'piso salarial', 'remuneracao minima', 'CF artigo 7o', 'reajuste salarial'],
    faq: [
      { question: 'Qual o valor do salario minimo em 2025?', answer: 'O salario minimo em 2025 e de R$ 1.518,00 conforme decreto federal de reajuste anual.' },
      { question: 'O salario minimo serve de base para quais beneficios?', answer: 'Seguro-desemprego, abono salarial PIS/PASEP, beneficios do INSS e adicional de insalubridade.' },
      { question: 'Existe um piso salarial maior que o minimo?', answer: 'Sim, diversas categorias tem pisos salariais definidos em convencoes coletivas, geralmente superiores ao minimo nacional.' },
    ],
    praticas: [
      'Verifique se seu salario e igual ou superior ao salario minimo vigente de R$ 1.518,00 para jornada integral',
      'Consulte a convencao coletiva da sua categoria para verificar se existe piso salarial superior ao minimo',
      'O adicional de insalubridade e calculado sobre o salario minimo',
    ],
    metaDescription: 'Salario minimo 2025: R$ 1.518,00. Direito fundamental no artigo 7o, IV da CF/88 e artigos 76-81 da CLT.',
  },
  {
    id: 'jornada-trabalho',
    slug: 'jornada-de-trabalho-clt',
    title: 'Jornada de Trabalho: Limites Legais e Jornadas Especiais',
    description: 'A jornada padrao e de 8 horas diarias e 44 horas semanais. Existem jornadas especiais para bancarios (6h), telemarketing (6h) e outras categorias.',
    content: 'A jornada de trabalho e regulada pelo artigo 7o, XIII da Constituicao Federal e artigos 58 a 75 da CLT. O limite constitucional e de 8 horas diarias e 44 horas semanais.\n\nExistem jornadas especiais para categorias como bancarios (6 horas diarias - art. 224 CLT), operadores de telemarketing (6 horas - NR-17) e jornalistas (5 horas - art. 303 CLT).\n\nA Reforma Trabalhista de 2017 autorizou a jornada 12x36 por acordo individual e o banco de horas por acordo individual. Turnos ininterruptos de revezamento tem jornada de 6 horas (art. 7o, XIV CF).\n\nA Sumula 85 do TST trata da compensacao de jornada. A jornada pode ser compensada por banco de horas em ate 6 meses por acordo individual ou 1 ano por acordo coletivo.',
    category: 'Jornada de Trabalho',
    cfArticle: 'Art. 7o, XIII e XIV - CF/88',
    cltArticles: 'Arts. 58 a 75 da CLT',
    icon: 'Clock',
    tags: ['jornada de trabalho', '44 horas semanais', 'carga horaria', 'jornada 12x36', 'bancarios 6 horas', 'banco de horas'],
    faq: [
      { question: 'Qual a jornada maxima de trabalho?', answer: '8 horas diarias e 44 horas semanais. Com horas extras, ate 10 horas diarias.' },
      { question: 'O que e a jornada 12x36?', answer: 'Regime de 12 horas de trabalho por 36 de descanso, autorizado por acordo individual desde a Reforma de 2017.' },
      { question: 'Qual a jornada dos bancarios?', answer: 'Bancarios tem jornada de 6 horas diarias e 30 horas semanais (art. 224 CLT).' },
      { question: 'Como funciona o banco de horas?', answer: 'Horas extras em um dia sao compensadas com folgas em outro. Pode ser por acordo individual (6 meses) ou coletivo (1 ano).' },
    ],
    praticas: [
      'Sua jornada padrao e de no maximo 8h diarias e 44h semanais',
      'Horas extras limitadas a 2h por dia',
      'Se voce trabalha em turnos de revezamento, tem direito a jornada reduzida de 6h',
      'O banco de horas deve ser registrado por escrito para ter validade',
    ],
    metaDescription: 'Jornada de trabalho CLT: 8 horas diarias, 44 horas semanais. Art. 7o, XIII e XIV CF/88 e arts. 58-75 CLT.',
  },
  {
    id: 'horas-extras',
    slug: 'horas-extras-direito-trabalhista',
    title: 'Horas Extras: Calculo, Adicionais e Reflexos Trabalhistas',
    description: 'Horas extras sao pagas com adicional minimo de 50% sobre a hora normal em dias uteis e 100% em domingos e feriados, respeitando o limite de 2 horas por dia.',
    content: 'O direito a horas extras esta previsto no artigo 7o, XVI da CF e artigo 59 da CLT. O adicional minimo e 50% em dias uteis e 100% em domingos e feriados.\n\nO limite e de 2 horas extras por dia. O calculo usa o divisor 220 para jornada de 44h semanais. Hora normal = salario / 220. Hora extra 50% = hora normal x 1,5.\n\nHoras extras habituais geram reflexos no DSR, ferias, 13o e FGTS conforme OJ 394 da SDI-1 do TST. A Sumula 264 do TST trata da integracao no calculo das ferias. A Sumula 124 do TST trata do divisor aplicavel.',
    category: 'Jornada de Trabalho',
    cfArticle: 'Art. 7o, XVI - CF/88',
    cltArticles: 'Art. 59 CLT / Sumula 124 e 264 TST / OJ 394 SDI-1',
    icon: 'Clock',
    tags: ['horas extras', 'adicional 50%', 'adicional 100%', 'calculo hora extra', 'divisor 220', 'reflexos horas extras'],
    faq: [
      { question: 'Qual o adicional minimo para horas extras?', answer: '50% em dias uteis e 100% em domingos e feriados.' },
      { question: 'Horas extras geram reflexo em outras verbas?', answer: 'Sim. Horas extras habituais integram DSR, ferias + 1/3, 13o salario, FGTS e aviso previo (OJ 394 da SDI-1 TST).' },
      { question: 'Como calcular a hora extra?', answer: 'Divida o salario por 220 (jornada 44h) para obter a hora normal. Multiplique por 1,5 para hora extra em dia util.' },
      { question: 'Qual o limite de horas extras por dia?', answer: 'Maximo de 2 horas extras por dia, nao podendo exceder 10 horas diarias.' },
    ],
    praticas: [
      'Calcule a hora normal dividindo o salario por 220 (jornada 44h)',
      'Hora extra em dia util: multiplique a hora normal por 1,5',
      'Hora extra em domingo/feriado: multiplique por 2',
      'Horas extras habituais geram reflexo no DSR, ferias, 13o e FGTS',
      'Mantenha registro de todos os horarios para comprovacao futura',
    ],
    metaDescription: 'Horas extras CLT: adicional de 50% e 100%, calculo passo a passo, divisor 220 e reflexos. Art. 59 CLT e OJ 394 SDI-1.',
  },
  {
    id: 'ferias-direito',
    slug: 'ferias-direito-trabalhador',
    title: 'Ferias: 30 Dias com 1/3 Constitucional, Parcelamento e Abono Pecuniario',
    description: 'Apos 12 meses de trabalho o empregado tem direito a 30 dias de ferias com adicional de 1/3 do salario. Saiba como funciona o periodo concessivo e parcelamento.',
    content: 'As ferias sao garantidas pelo artigo 7o, XVII da CF e artigos 129 a 153 da CLT. Sao 30 dias apos 12 meses de trabalho (periodo aquisitivo), com remuneracao acrescida de 1/3 constitucional.\n\nO periodo concessivo e de 12 meses apos o periodo aquisitivo. Se as ferias nao forem concedidas nesse prazo, devem ser pagas em dobro (art. 137 CLT e Sumula 7 do TST).\n\nAs ferias podem ser parceladas em ate 3 periodos (Reforma 2017): um de no minimo 14 dias e os demais no minimo 5 dias. O abono pecuniario permite vender 10 dias de ferias.\n\nFaltas nao justificadas reduzem os dias: 6 a 14 faltas = 24 dias; 15 a 23 = 18 dias; 24 a 32 = 12 dias; acima de 32 = perde o direito.',
    category: 'Remuneracao',
    cfArticle: 'Art. 7o, XVII - CF/88',
    cltArticles: 'Arts. 129 a 153 da CLT / Sumula 7 do TST',
    icon: 'Umbrella',
    tags: ['ferias', 'terco constitucional', 'abono pecuniario', 'ferias em dobro', 'periodo concessivo', 'parcelamento ferias'],
    faq: [
      { question: 'Quando as ferias sao pagas em dobro?', answer: 'Quando o empregador nao concede as ferias dentro do periodo concessivo de 12 meses (art. 137 CLT).' },
      { question: 'Como funciona o abono pecuniario?', answer: 'Permite converter 1/3 das ferias (10 dias) em dinheiro. Deve ser solicitado ate 15 dias antes do fim do periodo aquisitivo.' },
      { question: 'As ferias podem ser parceladas?', answer: 'Sim, em ate 3 periodos. Um periodo deve ter no minimo 14 dias, os demais no minimo 5 dias cada.' },
      { question: 'Faltas reduzem as ferias?', answer: 'Sim: 6-14 faltas = 24 dias; 15-23 = 18 dias; 24-32 = 12 dias; acima de 32 = perde o direito.' },
    ],
    praticas: [
      'Apos 12 meses voce tem direito a 30 dias de ferias + 1/3',
      'Voce pode vender 10 dias de ferias (abono pecuniario)',
      'Faltas nao justificadas reduzem seus dias de ferias',
      'Se o empregador nao conceder ferias em 12 meses, elas devem ser pagas em dobro',
    ],
    metaDescription: 'Ferias trabalhistas: 30 dias + 1/3 constitucional. Arts. 129-153 CLT e Art. 7o, XVII CF/88. Parcelamento e abono pecuniario.',
  },
  {
    id: 'fgts',
    slug: 'fgts-direitos-trabalhador',
    title: 'FGTS: Fundo de Garantia, Deposito, Multa e Saque',
    description: 'O empregador deposita 8% do salario mensalmente na conta vinculada. Na demissao sem justa causa o trabalhador recebe multa de 40% sobre o saldo total.',
    content: 'O FGTS e regido pela Lei 8.036/1990 e garantido pelo artigo 7o, III da CF. O empregador deposita 8% do salario do empregado em conta na Caixa Economica Federal ate o dia 20 de cada mes.\n\nNa dispensa sem justa causa: saque do saldo total mais multa de 40%. Na rescissao por acordo (art. 484-A CLT): multa de 20% e saque de 80%.\n\nO saque-aniversario permite sacar parte do FGTS anualmente no mes do aniversario. Quem opta por esta modalidade perde o direito ao saque integral na demissao.\n\nO FGTS tambem pode ser sacado para: casa propria, aposentadoria, doencas graves, falecimento (dependentes) e calamidade publica. A prescricao do FGTS e de 30 anos (contratos ate 2019) ou 5 anos (apos 2019) - Sumula 362 TST.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7o, III - CF/88',
    cltArticles: 'Lei 8.036/1990 / Sumula 362 TST',
    icon: 'PiggyBank',
    tags: ['FGTS', 'fundo de garantia', 'multa FGTS', 'saque FGTS', 'saque aniversario', 'multa 40%'],
    faq: [
      { question: 'Qual o percentual de deposito do FGTS?', answer: '8% do salario bruto mensalmente, depositado pelo empregador ate o dia 20.' },
      { question: 'Quanto e a multa do FGTS na demissao?', answer: '40% sobre o saldo na dispensa sem justa causa; 20% na rescissao por acordo.' },
      { question: 'O que e o saque-aniversario?', answer: 'Modalidade que permite sacar parte do FGTS anualmente. Quem opta perde o direito ao saque integral na demissao.' },
      { question: 'Qual o prazo para cobrar FGTS na Justica?', answer: '30 anos para contratos ate 2019; 5 anos para contratos a partir de 2019 (Sumula 362 TST).' },
    ],
    praticas: [
      'Consulte seu FGTS pelo aplicativo da Caixa Economica Federal',
      'Em caso de demissao sem justa causa, saque saldo total + multa de 40%',
      'Atencao: saque-aniversario impede o saque integral na demissao',
      'O FGTS pode ser usado para aquisicao de imovel proprio',
    ],
    metaDescription: 'FGTS: deposito de 8%, multa de 40%, saque-aniversario. Lei 8.036/1990, Art. 7o, III CF/88 e Sumula 362 TST.',
  },
  {
    id: 'adicional-noturno',
    slug: 'adicional-noturno-regras-clt',
    title: 'Adicional Noturno: 20% com Hora Reduzida e Prorrogacao',
    description: 'Adicional minimo de 20% sobre a hora normal para trabalho entre 22h e 5h, com reducao da hora noturna para 52 minutos e 30 segundos.',
    content: 'O adicional noturno e regulado pelo artigo 73 da CLT e artigo 7o, IX da CF. O periodo noturno para urbanos e das 22h as 5h. O adicional minimo e 20%.\n\nA hora noturna tem duracao de 52 minutos e 30 segundos - 7 horas relogio equivalem a 8 horas computadas. Para rurais: adicional de 25% e horario das 20h-4h (lavoura) ou 21h-5h (pecuaria).\n\nA Sumula 60 do TST garante o adicional noturno na prorrogacao apos as 5h quando o trabalhador iniciou a jornada no periodo noturno.\n\nO adicional noturno integra o salario para ferias, 13o, FGTS e aviso previo.',
    category: 'Adicionais Salariais',
    cfArticle: 'Art. 7o, IX - CF/88',
    cltArticles: 'Art. 73 CLT / Sumula 60 TST',
    icon: 'Moon',
    tags: ['adicional noturno', 'hora noturna', 'reducao hora noturna', 'periodo noturno', 'Sumula 60 TST'],
    faq: [
      { question: 'Qual o percentual do adicional noturno?', answer: '20% sobre a hora normal para trabalhadores urbanos e 25% para rurais.' },
      { question: 'Como funciona a reducao da hora noturna?', answer: 'Cada hora noturna tem 52 minutos e 30 segundos. Sete horas trabalhadas a noite sao pagas como 8.' },
      { question: 'Qual o horario noturno?', answer: '22h as 5h para urbanos. Para rurais: 20h-4h (lavoura) e 21h-5h (pecuaria).' },
      { question: 'O adicional noturno incide na prorrogacao apos as 5h?', answer: 'Sim. Sumula 60 TST - se iniciou no periodo noturno, o adicional continua na prorrogacao.' },
    ],
    praticas: [
      'O adicional noturno e de no minimo 20% sobre a hora normal',
      'Cada hora noturna equivale a 52 minutos e meio',
      'O periodo noturno e das 22h as 5h para trabalhadores urbanos',
      'O adicional noturno integra o salario para todos os efeitos legais',
    ],
    metaDescription: 'Adicional noturno CLT: 20% sobre a hora normal, hora reduzida para 52min30s, Sumula 60 TST. Art. 73 CLT.',
  },
  {
    id: 'insalubridade',
    slug: 'adicional-de-insalubridade',
    title: 'Adicional de Insalubridade: Graus de Risco e Calculo',
    description: 'Adicional de 10% (minimo), 20% (medio) ou 40% (maximo) do salario minimo para trabalhadores expostos a agentes nocivos a saude.',
    content: 'O adicional de insalubridade e regulado pelo artigo 192 da CLT e NR-15. Os graus sao: minimo (10%), medio (20%) e maximo (40%) do salario minimo.\n\nEm 2025 com salario minimo de R$ 1.518,00: minimo R$ 151,80, medio R$ 303,60, maximo R$ 607,20.\n\nA caracterizacao exige pericia tecnica por medico do trabalho ou engenheiro de seguranca (Sumula 448 TST). Agentes insalubres: ruido, calor, quimicos, biologicos.\n\nO uso de EPIs pode neutralizar a insalubridade se eficazes e com fiscalizacao. Sumula Vinculante 4 STF: calculo sobre o salario minimo.',
    category: 'Adicionais Salariais',
    cfArticle: 'Art. 7o, XXIII - CF/88',
    cltArticles: 'Arts. 189-197 CLT / NR-15 / Sumula 448 TST',
    icon: 'AlertTriangle',
    tags: ['insalubridade', 'adicional insalubridade', 'NR-15', 'agentes nocivos', 'pericia tecnica', 'Sumula 448 TST'],
    faq: [
      { question: 'Quais os percentuais do adicional de insalubridade?', answer: '10% (minimo), 20% (medio) e 40% (maximo) do salario minimo.' },
      { question: 'O uso de EPIs elimina o adicional?', answer: 'Sim, se os EPIs neutralizarem completamente a insalubridade com fiscalizacao do uso.' },
      { question: 'A insalubridade e calculada sobre o salario minimo ou base?', answer: 'Sobre o salario minimo nacional (Sumula Vinculante 4 STF).' },
      { question: 'Como e feita a comprovacao?', answer: 'Por pericia tecnica de medico do trabalho ou engenheiro de seguranca.' },
    ],
    praticas: [
      'O adicional varia de 10% a 40% do salario minimo conforme o grau',
      'Com salario minimo de R$ 1.518,00: R$ 151,80 a R$ 607,20',
      'A caracterizacao exige pericia tecnica',
      'Atividades em hospitais, lixo urbano e produtos quimicos dao direito ao adicional',
    ],
    metaDescription: 'Adicional de insalubridade: 10%, 20% ou 40% do salario minimo. Arts. 189-197 CLT e NR-15.',
  },
  {
    id: 'periculosidade',
    slug: 'adicional-de-periculosidade',
    title: 'Adicional de Periculosidade: 30% para Atividades Perigosas',
    description: 'Adicional de 30% sobre o salario base para trabalhadores que lidam com inflamaveis, explosivos, energia eletrica e vigilancia.',
    content: 'O adicional de periculosidade e regulado pelo artigo 193 da CLT e NR-16. E de 30% sobre o salario base do empregado.\n\nAtividades perigosas: inflamaveis, explosivos, energia eletrica, vigilancia armada e motociclistas (NR-16 Anexo 5).\n\nA caracterizacao exige pericia tecnica (art. 195 CLT). Desde a Reforma de 2017, pode ser acumulado com insalubridade se houver previsao em acordo coletivo.\n\nSumula 364 TST: a exposicao deve ser habitual e intermitente. Exposicao eventual nao gera direito.',
    category: 'Adicionais Salariais',
    cfArticle: 'Art. 7o, XXIII - CF/88',
    cltArticles: 'Art. 193 CLT / NR-16 / Sumula 364 TST',
    icon: 'Zap',
    tags: ['periculosidade', 'adicional periculosidade', 'atividade perigosa', 'NR-16', 'inflamaveis', 'energia eletrica', 'Sumula 364 TST'],
    faq: [
      { question: 'Qual o valor do adicional de periculosidade?', answer: '30% sobre o salario base do empregado.' },
      { question: 'Pode acumular periculosidade e insalubridade?', answer: 'Sim, desde a Reforma de 2017 com previsao em acordo ou convencao coletiva.' },
      { question: 'Quem tem direito?', answer: 'Trabalhadores que lidam com inflamaveis, explosivos, energia eletrica, vigilancia armada e motociclistas.' },
      { question: 'Exposicao eventual gera direito?', answer: 'Nao. Sumula 364 TST - a exposicao eventual ou acidental nao gera direito ao adicional.' },
    ],
    praticas: [
      'O adicional e de 30% sobre o salario base',
      'Eletricistas, frentistas, vigilantes e motociclistas tem direito',
      'E possivel acumular periculosidade e insalubridade desde 2017',
      'A exposicao deve ser habitual - eventual nao gera direito',
    ],
    metaDescription: 'Adicional de periculosidade: 30% do salario base. NR-16, Art. 193 CLT, Sumula 364 TST.',
  },
  {
    id: 'aviso-previo',
    slug: 'aviso-previo-direito-trabalhista',
    title: 'Aviso Previo: 30 a 90 Dias com Proporcionalidade',
    description: 'Aviso previo de 30 a 90 dias conforme o tempo de servico, nas modalidades trabalhado (com reducao de jornada) ou indenizado.',
    content: 'O aviso previo esta previsto no artigo 7o, XXI da CF, Lei 12.506/2011 e artigos 487 a 491 da CLT.\n\nPrazo: 30 dias para contratos de ate 1 ano, mais 3 dias por ano adicional, limitado a 90 dias (Lei 12.506/2011).\n\nAviso trabalhado: reducao de 2h diarias ou 7 dias de folga para buscar novo emprego (art. 488 CLT). Aviso indenizado: empregador dispensa o cumprimento e paga os dias.\n\nDurante o aviso previo o contrato continua vigorando para todos os efeitos. Sumula 276 TST: aviso previo indenizado integra o tempo de servico.',
    category: 'Rescisao Contratual',
    cfArticle: 'Art. 7o, XXI - CF/88',
    cltArticles: 'Arts. 487-491 CLT / Lei 12.506/2011',
    icon: 'Bell',
    tags: ['aviso previo', 'aviso previo proporcional', 'aviso indenizado', 'reducao jornada', 'Lei 12506'],
    faq: [
      { question: 'Como calcular o aviso previo proporcional?', answer: '30 dias + 3 dias por ano adicional de servico, maximo 90 dias (Lei 12.506/2011).' },
      { question: 'Quais os direitos durante o aviso trabalhado?', answer: 'Reducao de 2h diarias ou 7 dias de folga, manutencao dos beneficios.' },
      { question: 'O aviso previo indenizado conta para ferias e 13o?', answer: 'Sim, o periodo integra o tempo de servico (Sumula 276 TST).' },
      { question: 'O que acontece se o empregado nao cumprir o aviso?', answer: 'O empregador pode descontar o valor correspondente das verbas rescissorias.' },
    ],
    praticas: [
      'Aviso previo minimo de 30 dias ate 90 dias conforme tempo de servico',
      'No aviso trabalhado voce tem direito a sair 2h mais cedo todos os dias',
      'O aviso previo indenizado conta como tempo de servico',
      'Durante o aviso previo os beneficios sao mantidos',
    ],
    metaDescription: 'Aviso previo: 30 a 90 dias com proporcionalidade. Lei 12.506/2011, Art. 7o, XXI CF/88.',
  },
  {
    id: 'seguro-desemprego',
    slug: 'seguro-desemprego-direito',
    title: 'Seguro-Desemprego: Parcelas, Valores e Regras de Solicitacao',
    description: 'Beneficio de 3 a 7 parcelas ao trabalhador dispensado sem justa causa. Valor calculado pela media dos ultimos 3 salarios.',
    content: 'O seguro-desemprego e garantido pelo artigo 7o, II da CF e Lei 7.998/1990. O numero de parcelas varia conforme o tempo trabalhado.\n\nRegras: primeira solicitacao = 4 a 6 parcelas; segunda = 3 a 5; terceira em diante = 3 a 5. O valor e calculado pela media dos 3 ultimos salarios.\n\nPrazo para solicitacao: do 7o ao 120o dia apos a dispensa, pelo Gov.br ou app Carteira de Trabalho Digital.\n\nNao tem direito: quem pediu demissao, foi dispensado por justa causa, recebe beneficio INSS ou tem renda propria.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7o, II - CF/88',
    cltArticles: 'Lei 7.998/1990',
    icon: 'Briefcase',
    tags: ['seguro desemprego', 'parcelas seguro', 'calculo seguro desemprego', 'Gov.br', 'dispensa sem justa causa'],
    faq: [
      { question: 'Quantas parcelas do seguro-desemprego?', answer: '3 a 7 parcelas conforme tempo trabalhado e numero de solicitacoes ja realizadas.' },
      { question: 'Qual o prazo para solicitar?', answer: 'Do 7o ao 120o dia apos a dispensa, pelo app Carteira de Trabalho Digital ou site Gov.br.' },
      { question: 'Como e calculado o valor?', answer: 'Media dos 3 ultimos salarios com aplicacao de faixas definidas pelo CODEFAT.' },
      { question: 'Quem nao tem direito?', answer: 'Quem pediu demissao, foi dispensado por justa causa, recebe beneficio INSS ou tem renda propria.' },
    ],
    praticas: [
      'Solicite do 7o ao 120o dia apos a dispensa - nao perca o prazo!',
      'Faca a solicitacao online pelo Gov.br',
      'Tenha em maos o requerimento SD fornecido pelo empregador',
      'Para primeira solicitacao: 12 meses trabalhados nos ultimos 36 meses',
    ],
    metaDescription: 'Seguro-desemprego: 3 a 7 parcelas, como solicitar e calcular o valor. Art. 7o, II CF/88 e Lei 7.998/1990.',
  },
  {
    id: 'estabilidade-provisoria',
    slug: 'estabilidade-provisoria-emprego',
    title: 'Estabilidade Provisoria: Gestante, CIPA, Acidentado e Dirigente Sindical',
    description: 'A estabilidade provisoria impede a dispensa sem justa causa durante periodo determinado. Gestante, CIPA, acidentado e dirigente sindical.',
    content: 'A estabilidade provisoria impede a dispensa sem justa causa do trabalhador durante periodo determinado.\n\nGestante: da confirmacao da gravidez ate 5 meses apos o parto (ADCT art. 10, II, b). Sumula 244 TST: desconhecimento da gravidez nao afasta o direito. Vale para contrato temporario e experiencia.\n\nMembro CIPA: da candidatura ate 1 ano apos o mandato (art. 165 CLT, Sumula 339 TST).\n\nAcidentado: 12 meses apos o retorno ao trabalho (art. 118 Lei 8.213/91, Sumula 378 TST).\n\nDirigente sindical: durante o mandato (art. 543 CLT, Sumula 369 TST). Representante de empregados nas empresas com mais de 200 funcionarios (art. 510-B CLT).',
    category: 'Contrato de Trabalho',
    cfArticle: 'Art. 7o, I - CF/88',
    cltArticles: 'Arts. 165, 510-B, 543 CLT / ADCT Art. 10, II, b / Leis 8.213/91',
    icon: 'Shield',
    tags: ['estabilidade', 'gestante', 'CIPA', 'acidente de trabalho', 'dirigente sindical', 'Sumula 244 TST'],
    faq: [
      { question: 'Quem tem direito a estabilidade?', answer: 'Gestante, membro CIPA, acidentado de trabalho, dirigente sindical e representante de empregados.' },
      { question: 'A gestante tem estabilidade em contrato temporario?', answer: 'Sim, Sumula 244, II TST. A estabilidade vale independentemente da modalidade contratual.' },
      { question: 'Quanto tempo dura a estabilidade do acidentado?', answer: '12 meses apos o retorno ao trabalho (art. 118 Lei 8.213/91).' },
      { question: 'Empregado publico tem estabilidade?', answer: 'Empregados de empresas publicas e sociedades de economia mista nao tem estabilidade, salvo previsao legal.' },
    ],
    praticas: [
      'Gestante: estabilidade da gravidez ate 5 meses apos o parto',
      'Membro CIPA: da candidatura ate 1 ano apos o mandato',
      'Acidentado: 12 meses apos o retorno',
      'Importante: so protege contra dispensa sem justa causa',
    ],
    metaDescription: 'Estabilidade provisoria: gestante (Sumula 244 TST), CIPA, acidentado e dirigente sindical.',
  },
  {
    id: 'rescissao-contratual',
    slug: 'rescissao-contratual-tipos-verbas',
    title: 'Rescisao Contratual: Tipos de Desligamento e Verbas Devidas',
    description: 'Cada tipo de desligamento gera direitos diferentes: sem justa causa, justa causa, pedido de demissao e acordo.',
    content: 'A rescissao contratual e regulada pelos artigos 477 a 486 da CLT.\n\nDispensa sem justa causa: saldo de salario, aviso previo, ferias + 1/3, 13o proporcional, multa de 40% FGTS, saque integral FGTS e seguro-desemprego.\n\nDispensa por justa causa (art. 482 CLT): apenas saldo de salario e ferias vencidas + 1/3.\n\nPedido de demissao: saldo, ferias + 1/3, 13o proporcional e saque FGTS. Sem multa nem seguro-desemprego.\n\nRescisao por acordo (art. 484-A CLT): saldo, ferias, 13o, aviso previo pela metade, multa de 20% FGTS, saque de 80%. Sem seguro-desemprego.\n\nPrazo para pagamento: 10 dias corridos (art. 477, par. 6o CLT). Atraso gera multa de um salario.',
    category: 'Rescisao Contratual',
    cfArticle: 'Art. 7o, I e XXI - CF/88',
    cltArticles: 'Arts. 477-486 CLT / Art. 484-A CLT',
    icon: 'FileText',
    tags: ['rescissao', 'dispensa', 'justa causa', 'pedido demissao', 'acordo rescissorio', 'verbas rescissorias'],
    faq: [
      { question: 'Quais os direitos na dispensa sem justa causa?', answer: 'Saldo, aviso previo, ferias + 1/3, 13o proporcional, multa 40% FGTS, saque FGTS e seguro-desemprego.' },
      { question: 'Como funciona a rescissao por acordo?', answer: 'Multa de 20% FGTS, saque de 80%, aviso previo pela metade. Sem seguro-desemprego.' },
      { question: 'Quais os direitos na justa causa?', answer: 'Apenas saldo de salario e ferias vencidas + 1/3.' },
      { question: 'Qual o prazo para pagamento?', answer: 'Ate 10 dias corridos apos o termino do contrato. Atraso gera multa.' },
    ],
    praticas: [
      'Na dispensa sem justa causa: multa de 40% FGTS e seguro-desemprego',
      'Prazo de pagamento: 10 dias corridos apos o termino do contrato',
      'Na justa causa: apenas saldo de salario e ferias vencidas',
      'Na rescissao por acordo: multa de 20% FGTS e aviso previo pela metade',
    ],
    metaDescription: 'Rescisao contratual: tipos de desligamento e verbas devidas. Arts. 477-486 CLT.',
  },
  {
    id: 'intervalo-intrajornada',
    slug: 'intervalo-intrajornada-clt',
    title: 'Intervalo Intrajornada: Direito ao Descanso para Refeicao',
    description: 'Intervalo obrigatorio de 1 hora para jornadas acima de 6 horas e 15 minutos para jornadas de 4 a 6 horas. A nao concessao gera pagamento como hora extra.',
    content: 'O intervalo intrajornada e regulado pelo artigo 71 da CLT e Sumula 437 TST.\n\nPara jornadas acima de 6h: minimo 1 hora. Para 4h a 6h: 15 minutos. Para ate 4h: nao obrigatorio.\n\nSe nao concedido: pagamento como hora extra com adicional de 50% (Sumula 437, I TST).\n\nTema 1046 STF: a reducao por acordo coletivo e valida desde que respeitado o minimo de 30 minutos.\n\nIntervalo interjornada: minimo 11 horas entre jornadas (art. 66 CLT).',
    category: 'Jornada de Trabalho',
    cfArticle: 'Art. 7o, XIII - CF/88',
    cltArticles: 'Arts. 66-72 CLT / Sumula 437 TST',
    icon: 'Coffee',
    tags: ['intervalo intrajornada', 'almoco', 'descanso', 'Sumula 437 TST', 'intervalo interjornada'],
    faq: [
      { question: 'Qual a duracao do intervalo intrajornada?', answer: '1h para jornadas acima de 6h, 15 min para 4h a 6h.' },
      { question: 'O que acontece se o intervalo nao for concedido?', answer: 'Pagamento como hora extra com adicional de 50% (Sumula 437 TST).' },
      { question: 'O intervalo pode ser reduzido por acordo coletivo?', answer: 'Sim. Tema 1046 STF validou reducao para minimo 30 minutos com contrapartida.' },
      { question: 'Qual o intervalo entre uma jornada e outra?', answer: 'Minimo 11 horas consecutivas (intervalo interjornada - art. 66 CLT).' },
    ],
    praticas: [
      'Para jornadas acima de 6h voce tem direito a no minimo 1h de intervalo',
      'O intervalo nao e computado na jornada de trabalho',
      'Se seu intervalo e reduzido, voce tem direito a receber como hora extra',
      'O descanso entre um dia e outro deve ser de no minimo 11 horas',
    ],
    metaDescription: 'Intervalo intrajornada CLT: 1h para jornadas acima de 6h. Sumula 437 TST. Arts. 66-72 CLT.',
  },
  {
    id: 'licenca-maternidade',
    slug: 'licenca-maternidade-direito',
    title: 'Licenca-Maternidade: 120 Dias com Salario Integral e Estabilidade',
    description: '120 dias de licenca com salario integral e estabilidade desde a gravidez ate 5 meses apos o parto. Programa Empresa Cidada amplia para 180 dias.',
    content: 'A licenca-maternidade e garantida pelo artigo 7o, XVIII da CF e artigos 391 a 400 da CLT. Sao 120 dias (180 dias no Programa Empresa Cidada - Lei 11.770/2008).\n\nO salario-maternidade e pago pelo INSS ou pelo empregador que compensa com a contribuicao previdenciaria.\n\nEstabilidade da gestante: da confirmacao da gravidez ate 5 meses apos o parto (ADCT art. 10, II, b). Sumula 244 TST: desconhecimento da gravidez nao afasta o direito. Vale para contrato de experiencia e temporario.\n\nAborto nao criminoso: 2 semanas de repouso (art. 395 CLT).',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7o, XVIII - CF/88',
    cltArticles: 'Arts. 391-400 CLT / ADCT Art. 10, II, b / Lei 11.770/2008',
    icon: 'Heart',
    tags: ['licenca maternidade', 'gestante', 'estabilidade gestante', 'salario maternidade', 'Sumula 244 TST'],
    faq: [
      { question: 'Quanto tempo dura a licenca-maternidade?', answer: '120 dias (180 dias no Programa Empresa Cidada).' },
      { question: 'A gestante tem estabilidade?', answer: 'Sim, da confirmacao da gravidez ate 5 meses apos o parto (ADCT Art. 10, II, b).' },
      { question: 'A gestante tem estabilidade no contrato de experiencia?', answer: 'Sim, Sumula 244, III TST. A estabilidade vale para qualquer tipo de contrato.' },
      { question: 'O que acontece em caso de aborto nao criminoso?', answer: '2 semanas de repouso com salario normal (art. 395 CLT).' },
    ],
    praticas: [
      'Licenca de 120 dias com salario integral, 180 dias via Empresa Cidada',
      'Estabilidade da gravidez ate 5 meses apos o parto',
      'Comunique a gravidez assim que confirmada',
      'O desconhecimento pelo empregador nao elimina a estabilidade',
    ],
    metaDescription: 'Licenca-maternidade: 120 a 180 dias com salario integral e estabilidade. Art. 7o, XVIII CF/88. Sumula 244 TST.',
  },
  {
    id: 'decimo-terceiro',
    slug: 'decimo-terceiro-salario',
    title: '13o Salario: Calculo, Prazos e Descontos',
    description: 'Pago em duas parcelas: primeira ate 30/11 (sem descontos) e segunda ate 20/12 (com INSS e IRRF). Valor proporcional aos meses trabalhados.',
    content: 'O 13o salario e garantido pelo artigo 7o, VIII da CF e Leis 4.090/1962 e 4.749/1965.\n\nO valor corresponde a 1/12 da remuneracao por mes trabalhado (ou fracao igual ou superior a 15 dias).\n\nParcelas: 1a ate 30/11 sem descontos (metade do salario); 2a ate 20/12 com INSS e IRRF.\n\nHoras extras habituais integram o calculo (Sumula 45 TST). FGTS incide sobre o valor total.\n\nNa rescissao: 13o proporcional devido na dispensa sem justa causa, pedido de demissao e acordo. Na justa causa, nao.',
    category: 'Remuneracao',
    cfArticle: 'Art. 7o, VIII - CF/88',
    cltArticles: 'Lei 4.090/1962 / Lei 4.749/1965 / Sumula 45 TST',
    icon: 'Gift',
    tags: ['13o salario', 'gratificacao natalina', 'decimo terceiro', 'calculo 13o', 'primeira parcela', 'segunda parcela'],
    faq: [
      { question: 'Quando o 13o deve ser pago?', answer: '1a parcela ate 30/11 (sem descontos), 2a parcela ate 20/12 (com INSS e IRRF).' },
      { question: 'Como calcular o 13o proporcional?', answer: 'Divida o salario por 12 e multiplique pelos meses trabalhados. Mes com 15+ dias conta como cheio.' },
      { question: 'Horas extras integram o 13o?', answer: 'Sim, horas extras habituais integram o calculo (Sumula 45 TST).' },
      { question: 'Quem tem direito ao 13o na rescissao?', answer: 'Dispensa sem justa causa, pedido de demissao e acordo. Na justa causa nao.' },
    ],
    praticas: [
      '1a parcela sem descontos ate 30 de novembro',
      '2a parcela com INSS e IRRF ate 20 de dezembro',
      'O valor e proporcional aos meses trabalhados no ano',
      'Horas extras habituais aumentam o valor do 13o',
    ],
    metaDescription: '13o salario: calculo, prazos (30/11 e 20/12), descontos. Art. 7o, VIII CF/88. Leis 4.090/62 e 4.749/65.',
  },
  {
    id: 'prescricao-trabalhista',
    slug: 'prazo-prescricional-trabalhista',
    title: 'Prescricao Trabalhista: Prazos para Cobrar seus Direitos na Justica',
    description: 'Prazo de 5 anos durante o contrato e 2 anos apos a extincao para cobrar direitos na Justica do Trabalho.',
    content: 'A prescricao trabalhista e regida pelo artigo 7o, XXIX da CF e artigos 10 e 11 da CLT.\n\nDurante o contrato: 5 anos retroativos (prescricao quinquenal). Apos extincao: 2 anos para ajuizar a acao (prescricao bienal).\n\nFGTS: 30 anos para contratos ate 13/11/2019; 5 anos para contratos a partir de 14/11/2019 (Lei 13.932/2019 e Sumula 362 TST).\n\nDano moral: 3 anos (Tema 126 TST), observando-se a prescricao bienal apos extincao.\n\nMenores de 18 anos: o prazo prescricional comeca a contar quando completam 18 anos.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7o, XXIX - CF/88',
    cltArticles: 'Arts. 10 e 11 CLT / Sumula 362 TST / Tema 126 TST',
    icon: 'Calendar',
    tags: ['prescricao', 'prazo prescricional', 'Justica do Trabalho', 'prescricao bienal', 'prescricao quinquenal', 'Sumula 362 TST'],
    faq: [
      { question: 'Qual o prazo para ajuizar acao apos a demissao?', answer: '2 anos apos o termino do contrato (prescricao bienal).' },
      { question: 'Qual o prazo para cobrar direitos durante o contrato?', answer: '5 anos retroativos do ajuizamento da acao.' },
      { question: 'Qual o prazo para cobrar FGTS?', answer: '30 anos para contratos ate 2019; 5 anos para contratos a partir de 2019 (Sumula 362 TST).' },
      { question: 'Dano moral prescreve em quanto tempo?', answer: '3 anos (Tema 126 TST), observando a prescricao bienal apos extincao.' },
    ],
    praticas: [
      'Durante o contrato: pode cobrar direitos dos ultimos 5 anos',
      'Apos demissao: 2 anos para entrar com a acao na Justica do Trabalho',
      'FGTS: 30 anos para contratos antigos, 5 anos para novos',
      'Nao deixe para depois: a prescricao e fatal',
    ],
    metaDescription: 'Prescricao trabalhista: 5 anos durante o contrato, 2 anos apos demissao. Art. 7o, XXIX CF/88.',
  },
  {
    id: 'reforma-trabalhista',
    slug: 'reforma-trabalhista-lei-13467',
    title: 'Reforma Trabalhista Lei 13.467/2017: Principais Mudancas na CLT',
    description: 'A Reforma alterou mais de 100 dispositivos da CLT: contribuicao sindical facultativa, parcelamento de ferias, rescissao por acordo e terceirizacao.',
    content: 'A Reforma Trabalhista (Lei 13.467/2017) alterou mais de 100 dispositivos da CLT.\n\nContribuicao sindical: facultativa, dependendo de autorizacao expressa do trabalhador.\n\nFerias: parceladas em ate 3 periodos (um de 14 dias, demais de 5 dias).\n\nRescisao por acordo (art. 484-A): multa de 20% FGTS, saque de 80%, sem seguro-desemprego.\n\nTerceirizacao: permitida para atividade-fim.\n\nContrato intermitente (art. 452-A): trabalho nao continuo com periodos de convocacao e inatividade.\n\nJornada 12x36: autorizada por acordo individual. Prevalencia do negociado sobre o legislado em diversos temas.',
    category: 'Contrato de Trabalho',
    cfArticle: 'Art. 7o - CF/88',
    cltArticles: 'Lei 13.467/2017',
    icon: 'FileText',
    tags: ['reforma trabalhista', 'Lei 13467', 'CLT 2017', 'contribuicao sindical', 'terceirizacao', 'contrato intermitente', 'rescissao por acordo'],
    faq: [
      { question: 'A contribuicao sindical ainda e obrigatoria?', answer: 'Nao. E facultativa desde 2017, dependendo de autorizacao expressa do trabalhador.' },
      { question: 'O que mudou na rescissao por acordo?', answer: 'Multa de 20% FGTS, saque de 80%, aviso previo pela metade. Sem seguro-desemprego.' },
      { question: 'O que e o contrato intermitente?', answer: 'Trabalho nao continuo com periodos alternados de convocacao e inatividade (art. 452-A CLT).' },
      { question: 'O que prevalece: acordo coletivo ou lei?', answer: 'Desde a Reforma, acordos e convencoes podem prevalecer sobre a CLT em varios temas.' },
    ],
    praticas: [
      'Contribuicao sindical nao e mais obrigatoria',
      'Ferias podem ser parceladas em ate 3 periodos',
      'Terceirizacao de atividade-fim e permitida desde 2017',
      'A rescissao por acordo existe: multa reduzida, sem seguro-desemprego',
    ],
    metaDescription: 'Reforma Trabalhista Lei 13.467/2017: contribuicao sindical facultativa, terceirizacao, contrato intermitente e mais.',
  },
  {
    id: 'contrato-experiencia',
    slug: 'contrato-de-experiencia-clt',
    title: 'Contrato de Experiencia: Prazos e Direitos',
    description: 'O contrato de experiencia tem prazo maximo de 90 dias, podendo ser prorrogado uma unica vez.',
    content: 'O contrato de experiencia e regulado pelos artigos 443, 445 e 451 da CLT. Prazo maximo de 90 dias, com uma unica prorrogacao.\n\nSe ultrapassar 90 dias, o contrato torna-se automaticamente por prazo indeterminado (art. 451 CLT).\n\nDireitos: salario, 13o proporcional, ferias proporcionais + 1/3, FGTS, repouso semanal e vale-transporte.\n\nNa dispensa sem justa causa durante o contrato: saldo, ferias proporcionais, 13o proporcional e saque FGTS. Sem aviso previo, multa 40% ou seguro-desemprego.\n\nSumula 244, III TST: gestante tem estabilidade mesmo no contrato de experiencia.',
    category: 'Contrato de Trabalho',
    cfArticle: 'Art. 7o - CF/88',
    cltArticles: 'Arts. 443, 445 e 451 CLT / Sumula 244 TST',
    icon: 'FileText',
    tags: ['contrato de experiencia', 'prazo determinado', '90 dias', 'prorrogacao', 'experiencia CLT'],
    faq: [
      { question: 'Qual o prazo maximo do contrato de experiencia?', answer: '90 dias, com uma unica prorrogacao dentro desse limite.' },
      { question: 'Quais os direitos durante o contrato?', answer: 'Salario, 13o, ferias + 1/3, FGTS, repouso semanal e vale-transporte.' },
      { question: 'O que acontece se ultrapassar 90 dias?', answer: 'O contrato torna-se automaticamente por prazo indeterminado (art. 451 CLT).' },
      { question: 'A gestante tem estabilidade no contrato de experiencia?', answer: 'Sim, Sumula 244, III TST - vale para qualquer modalidade contratual.' },
    ],
    praticas: [
      'O contrato pode ter no maximo 90 dias com uma prorrogacao',
      'Se passar de 90 dias, vira contrato por prazo indeterminado',
      'Na dispensa antecipada: sem aviso previo, multa 40% ou seguro-desemprego',
      'A gestante tem estabilidade mesmo no contrato de experiencia',
    ],
    metaDescription: 'Contrato de experiencia: prazo maximo de 90 dias. Arts. 443, 445 e 451 CLT.',
  },
  {
    id: 'teletrabalho-home-office',
    slug: 'teletrabalho-home-office-lei-14442',
    title: 'Teletrabalho e Home Office: Direitos e Deveres',
    description: 'O teletrabalho e regulado pelos artigos 75-A a 75-E da CLT, alterados pela Lei 14.442/2022.',
    content: 'O teletrabalho foi regulamentado pelos artigos 75-A a 75-E da CLT (Reforma 2017) e alterado pela Lei 14.442/2022.\n\nO comparecimento eventual a empresa nao descaracteriza o teletrabalho. O regime deve constar no contrato.\n\nControle de jornada: o teletrabalhador nao esta sujeito ao controle de jornada (art. 62, III CLT), salvo acordo em contrario.\n\nEquipamentos e despesas: o empregador deve arcar com custos de equipamentos e infraestrutura (art. 75-D CLT).\n\nReversao ao presencial: prazo de transicao minimo de 15 dias.',
    category: 'Contrato de Trabalho',
    cfArticle: 'Art. 7o - CF/88',
    cltArticles: 'Arts. 75-A a 75-E CLT / Lei 14.442/2022',
    icon: 'Home',
    tags: ['teletrabalho', 'home office', 'trabalho remoto', 'Lei 14442', 'equipamentos', 'CLT teletrabalho'],
    faq: [
      { question: 'Quem paga pelos equipamentos?', answer: 'O empregador deve arcar com custos de equipamentos e infraestrutura, salvo acordo (art. 75-D CLT).' },
      { question: 'O teletrabalhador tem direito a horas extras?', answer: 'Em regra, nao. Esta excluido do controle de jornada (art. 62, III CLT), salvo acordo especifico.' },
      { question: 'O que mudou com a Lei 14.442/2022?', answer: 'Esclareceu que o comparecimento eventual a empresa nao descaracteriza o teletrabalho.' },
      { question: 'Pode voltar ao presencial?', answer: 'Sim, o empregador pode reverter com transicao minima de 15 dias.' },
    ],
    praticas: [
      'O teletrabalho deve constar no contrato de trabalho',
      'Equipamentos sao de responsabilidade do empregador',
      'Comparecimento eventual nao descaracteriza o home office',
      'Em regra, nao ha direito a horas extras no teletrabalho',
    ],
    metaDescription: 'Teletrabalho e home office: arts. 75-A a 75-E CLT e Lei 14.442/2022.',
  },
  {
    id: 'assedio-moral',
    slug: 'assedio-moral-no-trabalho',
    title: 'Assedio Moral no Trabalho: O que Caracteriza e como Denunciar',
    description: 'O assedio moral e caracterizado por condutas abusivas reiteradas que atentam contra a dignidade do trabalhador.',
    content: 'O assedio moral e a conduta abusiva, reiterada e intencional que atenta contra a dignidade e integridade psiquica do trabalhador.\n\nTipos: vertical descendente (chefe contra subordinado), ascendente (subordinados contra chefe), horizontal (entre colegas) e institucional (praticas da empresa como politica).\n\nExemplos: criticas publicas constantes, isolamento, sobrecarga com prazos impossiveis, tarefas degradantes, ameacas de demissao constantes.\n\nPrejuizos: dano moral, dano material e rescissao indireta (art. 483 CLT).\n\nComo denunciar: reuna provas, registre no sindicato ou MPT, procure a Justica do Trabalho (prazo de 2 anos apos o fim do contrato).',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 1o, III e Art. 5o, X - CF/88',
    cltArticles: 'Arts. 482 e 483 CLT / CC arts. 186 e 927',
    icon: 'UserX',
    tags: ['assedio moral', 'humilhacao', 'dignidade', 'rescissao indireta', 'MPT', 'dano moral'],
    faq: [
      { question: 'O que caracteriza assedio moral?', answer: 'Conduta abusiva, reiterada e intencional que atenta contra a dignidade do trabalhador.' },
      { question: 'Qual a diferenca entre assedio moral e conflito normal?', answer: 'O assedio e reiterado, intencional e visa desestabilizar a vitima. Conflitos eventuais nao configuram assedio.' },
      { question: 'O que fazer em caso de assedio moral?', answer: 'Registre as ocorrencias, reuna provas, comunique o sindicato e procure o MPT.' },
      { question: 'Assedio moral pode gerar indenizacao?', answer: 'Sim, danos morais e materiais, alem de rescissao indireta (art. 483 CLT).' },
    ],
    praticas: [
      'Documente todas as situacoes constrangedoras com data, hora e testemunhas',
      'Reuna provas: emails, mensagens e gravacoes legais',
      'Comunique o sindicato da sua categoria',
      'Em casos graves, procure o Ministerio Publico do Trabalho',
    ],
    metaDescription: 'Assedio moral no trabalho: o que caracteriza, provas e como denunciar. Direitos do trabalhador.',
  },
  {
    id: 'equiparacao-salarial',
    slug: 'equiparacao-salarial-artigo-461',
    title: 'Equiparacao Salarial: Quando e Devida e Como Solicitar',
    description: 'A equiparacao salarial e devida quando dois empregados exercem a mesma funcao, com igual produtividade e perfeicao tecnica, para o mesmo empregador.',
    content: 'A equiparacao salarial esta prevista no artigo 461 CLT e Sumula 6 TST.\n\nRequisitos: mesmo empregador, mesma localidade, diferenca de tempo inferior a 2 anos, identidade de funcao, igual produtividade e perfeicao tecnica.\n\nO paradigma deve ser contemporaneo ao periodo da pretensao (Sumula 6, VIII TST).\n\nQuadro de carreira organizado pode afastar o direito, desde que haja regras claras de promocao (art. 461, par. 2o CLT).\n\nNao e possivel equiparacao em cadeia. O paradigma nao pode ter seu salario reduzido.',
    category: 'Remuneracao',
    cfArticle: 'Art. 7o, XXX e XXXI - CF/88',
    cltArticles: 'Art. 461 CLT / Sumula 6 TST',
    icon: 'Scale',
    tags: ['equiparacao salarial', 'isonomia salarial', 'artigo 461 CLT', 'Sumula 6 TST', 'paradigma', 'mesma funcao'],
    faq: [
      { question: 'Quais os requisitos para equiparacao salarial?', answer: 'Mesmo empregador, mesma localidade, diferenca de tempo inferior a 2 anos, identidade de funcao, igual produtividade.' },
      { question: 'O que e o paradigma na equiparacao?', answer: 'O colega que recebe salario maior e exerce a mesma funcao na mesma empresa.' },
      { question: 'O plano de cargos impede a equiparacao?', answer: 'Sim, se for organizado com promocao por antiguidade e merecimento (art. 461, par. 2o CLT).' },
      { question: 'Qual o prazo para pedir equiparacao?', answer: 'Prescricao bienal (2 anos apos demissao) e quinquenal (5 anos durante o contrato).' },
    ],
    praticas: [
      'Identifique um colega com mesma funcao e salario maior',
      'Reuna provas de que exerce as mesmas tarefas com igual produtividade',
      'A diferenca de tempo no cargo nao pode ser superior a 2 anos',
      'Se houver plano de carreira formal, a equiparacao pode nao ser cabivel',
    ],
    metaDescription: 'Equiparacao salarial: art. 461 CLT e Sumula 6 TST. Requisitos e como solicitar.',
  },
  {
    id: 'justa-causa',
    slug: 'demissao-por-justa-causa',
    title: 'Demissao por Justa Causa: Causas, Efeitos e Defesa do Trabalhador',
    description: 'A justa causa e a falta grave que autoriza o empregador a rescindir o contrato sem pagamento da maioria das verbas rescissorias.',
    content: 'A justa causa do empregado esta no artigo 482 CLT: improbidade, mau procedimento, desidia, embriaguez habitual, violacao de segredo, insubordinacao, abandono de emprego, ofensas fisicas, atividades concorrentes.\n\nEfeitos: perde aviso previo, 13o, ferias proporcionais + 1/3, multa 40% FGTS e seguro-desemprego. So recebe saldo de salario e ferias vencidas + 1/3.\n\nExige: imediatidade, proporcionalidade e singularidade.\n\nAbandono de emprego: presume-se apos 30 dias consecutivos sem justificativa.\n\nRescisao indireta (art. 483 CLT): empregado pede demissao por culpa do empregador (atraso salarial, assedio moral, etc.) mantendo todos os direitos.',
    category: 'Rescisao Contratual',
    cfArticle: 'Art. 7o - CF/88',
    cltArticles: 'Arts. 482 a 484 CLT',
    icon: 'AlertTriangle',
    tags: ['justa causa', 'demissao por justa causa', 'artigo 482 CLT', 'rescissao indireta', 'abandono de emprego'],
    faq: [
      { question: 'Quais as causas de justa causa?', answer: 'Improbidade, desidia, insubordinacao, abandono de emprego, embriaguez habitual, violacao de segredo (art. 482 CLT).' },
      { question: 'Quais direitos o empregado perde?', answer: 'Perde aviso previo, 13o, ferias proporcionais + 1/3, multa 40% FGTS e seguro-desemprego.' },
      { question: 'O que e rescissao indireta?', answer: 'Empregado pede demissao por culpa do empregador (atraso salarial, assedio moral - art. 483 CLT).' },
      { question: 'Quantos dias de falta caracterizam abandono?', answer: '30 dias consecutivos sem justificativa, com notificacao do empregador.' },
    ],
    praticas: [
      'Na justa causa voce perde a maioria dos direitos',
      'A justa causa exige gravidade, imediatidade e proporcionalidade',
      'Se o empregador atrasa salarios, voce pode pedir rescissao indireta',
      'Toda justa causa pode ser questionada judicialmente',
    ],
    metaDescription: 'Demissao por justa causa: causas (art. 482 CLT), efeitos e direitos perdidos.',
  },
  {
    id: 'adicional-transferencia',
    slug: 'adicional-de-transferencia',
    title: 'Adicional de Transferencia: Direitos do Trabalhador Removido',
    description: 'O adicional de transferencia e devido quando o empregador transfere o trabalhador para outra localidade de forma provisoria, no minimo 25% do salario.',
    content: 'O adicional de transferencia esta previsto no artigo 469 CLT. E devido quando a transferencia for provisoria e nao solicitada pelo empregado.\n\nValor minimo: 25% do salario durante todo o periodo da transferencia.\n\nTransferencia definitiva: nao gera adicional, salvo prejuizo comprovado. Reforma 2017: permitiu transferencia sem adicional com acordo entre as partes.\n\nDespesas de transporte e mudanca correm por conta do empregador (art. 470 CLT).\n\nSumula 43 TST: adicional devido mesmo se transferido para localidade que tambem seja sede da empresa.',
    category: 'Remuneracao',
    cfArticle: 'Art. 7o - CF/88',
    cltArticles: 'Arts. 469 e 470 CLT / Sumula 43 TST',
    icon: 'MapPin',
    tags: ['adicional transferencia', 'transferencia provisoria', 'artigo 469 CLT', '25%', 'Sumula 43 TST'],
    faq: [
      { question: 'Qual o valor do adicional de transferencia?', answer: 'No minimo 25% do salario durante todo o periodo provisorio da transferencia.' },
      { question: 'Toda transferencia gera adicional?', answer: 'Nao. So a provisoria e nao solicitada pelo empregado. Definitiva nao gera.' },
      { question: 'Quem paga as despesas de mudanca?', answer: 'O empregador (art. 470 CLT).' },
      { question: 'O que mudou com a Reforma de 2017?', answer: 'Permitiu transferencia sem adicional com acordo entre as partes (art. 469, par. 1o alterado).' },
    ],
    praticas: [
      'O adicional e de no minimo 25% do salario para transferencia provisoria',
      'Transferencia definitiva nao gera direito ao adicional',
      'O empregador deve pagar transporte e mudanca',
      'Se voce solicitou a transferencia, nao tem direito ao adicional',
    ],
    metaDescription: 'Adicional de transferencia: 25% do salario. Arts. 469-470 CLT e Sumula 43 TST.',
  },
  {
    id: 'dano-moral-trabalhista',
    slug: 'dano-moral-trabalhista-indenizacao',
    title: 'Dano Moral Trabalhista: Indenizacao por Assedio, Discriminacao e Acidentes',
    description: 'O dano moral trabalhista ocorre quando o empregador ou colegas causam sofrimento psiquico ao trabalhador.',
    content: 'O dano moral trabalhista e a lesao a direitos da personalidade (honra, imagem, dignidade) decorrente da relacao de emprego. Fundamento: art. 5o, V e X CF e arts. 186 e 927 CC.\n\nTeto CLT (Reforma 2017): leve (ate 3 salarios), media (ate 5), grave (ate 20), gravissima (ate 50).\n\nCausas: assedio moral/sexual, discriminacao, acidente de trabalho, doenca ocupacional, revista vexatoria, cobranca abusiva de metas.\n\nO dano e presumido (in re ipsa) - basta provar a conduta ofensiva.\n\nDiscriminacao na contratacao: Lei 9.029/1995.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 5o, V e X - CF/88',
    cltArticles: 'Arts. 223-A a 223-G CLT / CC arts. 186 e 927',
    icon: 'Heart',
    tags: ['dano moral', 'indenizacao', 'assedio', 'discriminacao', 'CLT arts. 223-A a 223-G'],
    faq: [
      { question: 'Quais os valores da indenizacao?', answer: 'Leve: ate 3 salarios; Media: ate 5; Grave: ate 20; Gravíssima: ate 50 salarios (art. 223-G CLT).' },
      { question: 'O que causa dano moral?', answer: 'Assedio moral/sexual, discriminacao, acidente, doenca ocupacional, revista vexatoria.' },
      { question: 'Precisa provar o dano?', answer: 'Nao. O dano moral e presumido (in re ipsa) - basta provar a conduta ofensiva.' },
      { question: 'Discriminacao na contratacao gera indenizacao?', answer: 'Sim, Lei 9.029/1995.' },
    ],
    praticas: [
      'Documente as situacoes com provas (emails, testemunhas, prints)',
      'O dano moral independe de prova de prejuizo',
      'Os tetos variam de 3 a 50 salarios conforme a gravidade',
      'Discriminacao racial, de genero ou orientacao sexual gera indenizacao',
    ],
    metaDescription: 'Dano moral trabalhista: tetos de indenizacao (3 a 50 salarios). Arts. 223-A a 223-G CLT.',
  },
  {
    id: 'licenca-paternidade',
    slug: 'licenca-paternidade-trabalhista',
    title: 'Licenca-Paternidade: 5 Dias e Ampliacao para 20 Dias',
    description: 'A licenca-paternidade e de 5 dias corridos, ampliavel para 20 dias no Programa Empresa Cidada.',
    content: 'A licenca-paternidade esta prevista no ADCT art. 10, par. 1o e Lei 8.213/1991. Prazo: 5 dias corridos.\n\nPrograma Empresa Cidada (Lei 11.770/2008): amplia para 20 dias. Empregado deve solicitar em ate 2 dias uteis apos o nascimento.\n\nVale para adocao (Sumula 17 TST).\n\nNao ha estabilidade do pai na licenca-paternidade.\n\nPai solo: decisoes recentes do TST reconhecem direito a licenca de 120 dias por equiparacao a licenca-maternidade.',
    category: 'Direitos Fundamentais',
    cfArticle: 'Art. 7o, XIX - CF/88',
    cltArticles: 'ADCT Art. 10, par. 1o / Lei 11.770/2008 / Sumula 17 TST',
    icon: 'UserCheck',
    tags: ['licenca paternidade', '5 dias', 'empresa cidada', '20 dias', 'pai', 'adocao'],
    faq: [
      { question: 'Quantos dias de licenca-paternidade?', answer: '5 dias corridos (prazo legal), ampliavel para 20 dias no Programa Empresa Cidada.' },
      { question: 'O pai tem estabilidade no emprego?', answer: 'Nao. Diferente da gestante, o pai nao tem estabilidade durante a licenca.' },
      { question: 'A licenca vale para adocao?', answer: 'Sim, mesmo prazo (Sumula 17 TST).' },
      { question: 'O pai solo tem direito a licenca ampliada?', answer: 'Decisoes recentes do TST reconhecem direito a 120 dias por equiparacao.' },
    ],
    praticas: [
      'A licenca padrao e de 5 dias corridos',
      'Verifique se sua empresa participa do Programa Empresa Cidada (20 dias)',
      'Solicite a ampliacao em ate 2 dias uteis apos o nascimento',
      'O pai nao tem estabilidade no emprego',
    ],
    metaDescription: 'Licenca-paternidade: 5 dias (ampliavel para 20). ADCT Art. 10, par. 1o e Lei 11.770/2008.',
  },
  {
    id: 'plr-participacao-lucros',
    slug: 'plr-participacao-lucros-resultados',
    title: 'PLR: Participacao nos Lucros e Resultados',
    description: 'A PLR e um direito dos trabalhadores previsto no artigo 7o, XI da CF e Lei 10.101/2000. Nao tem natureza salarial e nao incide FGTS, INSS ou IRRF.',
    content: 'A PLR esta prevista no artigo 7o, XI da CF e Lei 10.101/2000. E uma remuneracao variavel que nao se incorpora ao salario.\n\nNao tem natureza salarial: nao incide FGTS, INSS ou IRRF. Nao integra o calculo de ferias, 13o ou aviso previo.\n\nDepende de negociacao entre empresa e empregados (comissao eleita ou sindicato). Metas pre-definidas.\n\nPeriodicidade: ate 2 vezes ao ano, com intervalos nao inferiores a um trimestre.\n\nDemitido tem direito proporcional, salvo disposicao em contrario no acordo.',
    category: 'Remuneracao',
    cfArticle: 'Art. 7o, XI - CF/88',
    cltArticles: 'Lei 10.101/2000',
    icon: 'TrendingUp',
    tags: ['PLR', 'participacao lucros', 'resultados', 'Lei 10101', 'metas', 'nao incide FGTS'],
    faq: [
      { question: 'A PLR tem desconto de INSS e IRRF?', answer: 'Nao. Nao tem natureza salarial - nao incide FGTS, INSS ou IRRF.' },
      { question: 'A PLR pode ser paga quantas vezes ao ano?', answer: 'Ate 2 vezes ao ano, com intervalos nao inferiores a um trimestre.' },
      { question: 'A PLR integra o salario?', answer: 'Nao. Nao se incorpora ao salario para ferias, 13o, aviso previo ou outras verbas.' },
      { question: 'Demitido tem direito a PLR proporcional?', answer: 'Sim, salvo disposicao em contrario no acordo coletivo.' },
    ],
    praticas: [
      'A PLR nao tem desconto de INSS, FGTS ou IRRF',
      'Verifique sua convencao coletiva para as regras da sua categoria',
      'As metas devem ser claras e pre-definidas',
      'O valor nao se incorpora ao salario',
    ],
    metaDescription: 'PLR: Participacao nos Lucros e Resultados. Art. 7o, XI CF/88 e Lei 10.101/2000.',
  },
];
