import type { Jurisprudencia } from './types';

export const jurisprudenciaCategorias = [
  { id: 'verbas-rescisorias', name: 'Verbas Rescisórias e Multas' },
  { id: 'adicionais', name: 'Adicionais e Remuneração' },
  { id: 'gestante-saude', name: 'Gestantes e Saúde do Trabalhador' },
  { id: 'processual', name: 'Direito Processual do Trabalho' },
  { id: 'jornada', name: 'Jornada e Condições de Trabalho' },
];

export const jurisprudencias: Jurisprudencia[] = [
  {
    id: 'tema-127',
    titulo: 'Tema 127 - Multa do Art. 477, §8º da CLT',
    tema: 'Tema 127 - Recurso de Revista Repetitivo',
    tese: 'A multa prevista no art. 477, §8º, da CLT é devida se o empregador não entregar os documentos de comunicação da extinção contratual aos órgãos competentes no prazo de 10 dias, mesmo que as verbas rescisórias em dinheiro tenham sido pagas tempestivamente.',
    descricao: 'O Tribunal Superior do Trabalho fixou a tese de que a multa do artigo 477, §8º da CLT é devida quando o empregador não entrega os documentos necessários para o saque do FGTS e requerimento do seguro-desemprego no prazo de 10 dias, independentemente do pagamento das verbas rescisórias em dinheiro ter sido feito no prazo. A tese foi fixada em julgamento de recurso repetitivo, tendo caráter vinculante para todos os Tribunais Regionais do Trabalho.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - Subseção de Dissídios Individuais',
    categoria: 'Verbas Rescisórias e Multas',
    tags: ['multa', 'art. 477 CLT', 'verbas rescisórias', 'documentos', 'prazo'],
    relator: 'Ministro Relator designado pelo TST',
    metaDescription: 'Tema 127 do TST: Multa do art. 477, §8º da CLT é devida mesmo com pagamento em dia, se os documentos rescisórios não forem entregues.',
  },
  {
    id: 'tema-120',
    titulo: 'Tema 120 - Multa do Art. 467 da CLT',
    tema: 'Tema 120 - Recurso de Revista Repetitivo',
    tese: 'A multa prevista no art. 467 da CLT não é devida quando há reconhecimento de vínculo empregatício em juízo e a natureza da relação jurídica foi impugnada na defesa.',
    descricao: 'O TST decidiu que a multa do artigo 467 da CLT (50% sobre o valor das verbas rescisórias incontroversas não pagas em primeira audiência) não é devida quando o reconhecimento do vínculo de emprego ocorre apenas em juízo e a defesa do empregador impugnou expressamente a natureza da relação jurídica. Nesse caso, as verbas são consideradas controversas, afastando a incidência da multa. A decisão foi proferida em sede de recurso repetitivo.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Verbas Rescisórias e Multas',
    tags: ['multa art. 467', 'vínculo empregatício', 'verbas incontroversas', 'repetitivo'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 120 do TST: Multa do art. 467 da CLT não é devida quando há reconhecimento de vínculo em juízo com impugnação na defesa.',
  },
  {
    id: 'tema-118',
    titulo: 'Tema 118 - Adicional de Insalubridade para Agentes de Saúde',
    tema: 'Tema 118 - Recurso de Revista Repetitivo',
    tese: 'Agentes comunitários de saúde têm direito ao adicional de insalubridade em grau médio, independentemente de laudo técnico, devido aos riscos inerentes à atividade.',
    descricao: 'O TST firmou o entendimento de que os agentes comunitários de saúde e agentes de combate às endemias têm direito ao adicional de insalubridade em grau médio (20% do salário mínimo), independentemente de laudo técnico pericial, em razão dos riscos inerentes à atividade de visitação domiciliar e exposição a agentes biológicos. A decisão baseia-se na Lei 13.342/2016 e na natureza da atividade exercida por esses profissionais, que envolve contato direto com a comunidade em áreas de risco.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Adicionais e Remuneração',
    tags: ['insalubridade', 'agente comunitário de saúde', 'agente de endemias', 'grau médio'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 118 do TST: Agentes comunitários de saúde têm direito ao adicional de insalubridade em grau médio, independentemente de laudo técnico.',
  },
  {
    id: 'tema-121',
    titulo: 'Tema 121 - Natureza Jurídica do Auxílio-Alimentação',
    tema: 'Tema 121 - Recurso de Revista Repetitivo',
    tese: 'O auxílio-alimentação não possui natureza salarial se o empregado contribui para o seu custeio, independentemente do valor da coparticipação.',
    descricao: 'O TST decidiu que o auxílio-alimentação pago pelo empregador não tem natureza salarial quando há coparticipação do empregado no custeio, independentemente do valor dessa coparticipação. Isso significa que o valor não integra o salário para fins de reflexos em férias, 13º salário, FGTS e aviso prévio. A decisão uniformiza o entendimento sobre o tema, que era objeto de divergência entre as Turmas do TST.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Adicionais e Remuneração',
    tags: ['auxílio-alimentação', 'natureza salarial', 'coparticipação', 'vale-refeição'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 121 do TST: Auxílio-alimentação com coparticipação do empregado não tem natureza salarial, independentemente do valor.',
  },
  {
    id: 'tema-119',
    titulo: 'Tema 119 - Estabilidade da Gestante com Dúvida sobre Concepção',
    tema: 'Tema 119 - Recurso de Revista Repetitivo',
    tese: 'A garantia de emprego da gestante é preservada mesmo que haja dúvida objetiva sobre a data exata da concepção, desde que contemporânea ao contrato de trabalho.',
    descricao: 'O TST consolidou o entendimento de que a estabilidade provisória da gestante (art. 10, II, b do ADCT) é preservada mesmo quando existe dúvida objetiva sobre a data exata da concepção, desde que seja comprovado que a gravidez é contemporânea ao período do contrato de trabalho. A decisão amplia a proteção à gestante, evitando que questionamentos técnicos sobre a data da concepção prejudiquem o direito à estabilidade.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Gestantes e Saúde do Trabalhador',
    tags: ['gestante', 'estabilidade', 'concepção', 'ADCT art. 10', 'gravidez'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 119 do TST: Estabilidade da gestante é preservada mesmo com dúvida sobre data da concepção, desde que contemporânea ao contrato.',
  },
  {
    id: 'tema-125',
    titulo: 'Tema 125 - Estabilidade Acidentária sem Afastamento de 15 Dias',
    tema: 'Tema 125 - Recurso de Revista Repetitivo',
    tese: 'Para a garantia provisória de emprego (art. 118 da Lei 8.213/91), não é necessário o afastamento superior a 15 dias ou o recebimento de auxílio-doença acidentário, bastando o reconhecimento do nexo causal entre a doença e o trabalho após a dispensa.',
    descricao: 'Em importante decisão, o TST estabeleceu que a estabilidade acidentária de 12 meses (art. 118 da Lei 8.213/1991) não exige necessariamente o afastamento superior a 15 dias ou o recebimento de auxílio-doença acidentário (B91). Basta que seja reconhecido o nexo causal ou concausal entre a doença e o trabalho, ainda que esse reconhecimento ocorra após a dispensa do empregado. A tese amplia significativamente a proteção dos trabalhadores que desenvolvem doenças ocupacionais.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Gestantes e Saúde do Trabalhador',
    tags: ['estabilidade acidentária', 'doença ocupacional', 'nexo causal', 'art. 118'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 125 do TST: Estabilidade acidentária não exige afastamento de 15 dias, bastando nexo causal entre doença e trabalho.',
  },
  {
    id: 'tema-128',
    titulo: 'Tema 128 - Acúmulo de Função de Motorista e Cobrador',
    tema: 'Tema 128 - Recurso de Revista Repetitivo',
    tese: 'Motoristas de ônibus urbanos que acumulam a função de cobrador não têm direito ao acréscimo salarial por acúmulo de função.',
    descricao: 'O TST decidiu que motoristas de ônibus urbanos que, eventualmente, acumulam a função de cobrador (recebimento de passagens) não têm direito ao acréscimo salarial por acúmulo de função. A Corte entendeu que a atividade de cobrança de passagens é inerente e compatível com a função de motorista de transporte coletivo urbano, não configurando acúmulo de função que justifique acréscimo salarial.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Jornada e Condições de Trabalho',
    tags: ['acúmulo de função', 'motorista', 'cobrador', 'ônibus', 'transporte'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 128 do TST: Motorista de ônibus que acumula função de cobrador não tem direito a acréscimo salarial por acúmulo de função.',
  },
  {
    id: 'tema-122',
    titulo: 'Tema 122 - Cartões de Ponto do Empregado Doméstico',
    tema: 'Tema 122 - Recurso de Revista Repetitivo',
    tese: 'A falta de apresentação dos cartões de ponto pelo empregador doméstico gera presunção relativa de veracidade da jornada alegada pelo trabalhador.',
    descricao: 'O TST aplicou aos empregados domésticos o mesmo entendimento já consolidado para empregados urbanos: a ausência de apresentação dos controles de frequência pelo empregador doméstico gera presunção relativa de veracidade da jornada de trabalho alegada pelo empregado. O empregador pode elidir essa presunção mediante prova em contrário, mas o ônus probatório se inverte em caso de ausência dos registros de ponto.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Direito Processual do Trabalho',
    tags: ['empregado doméstico', 'cartão de ponto', 'jornada', 'ônus da prova', 'Lei Complementar 150'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 122 do TST: Falta de cartões de ponto do empregado doméstico gera presunção de veracidade da jornada alegada.',
  },
  {
    id: 'tema-126',
    titulo: 'Tema 126 - Prescrição do Dano Moral em Ricochete',
    tema: 'Tema 126 - Recurso de Revista Repetitivo',
    tese: 'Aplica-se a prescrição trienal (Código Civil) para ações de indenização por dano moral em ricochete (indireto ou reflexo) na Justiça do Trabalho.',
    descricao: 'O TST fixou a tese de que as ações de indenização por dano moral indireto ou reflexo (dano moral em ricochete) ajuizadas na Justiça do Trabalho seguem a prescrição trienal prevista no artigo 206, §3º, V do Código Civil, e não a prescrição trabalhista bienal ou quinquenal. Dano moral em ricochete é aquele sofrido por terceiros (familiares) em decorrência de dano causado ao trabalhador, como no caso de acidente de trabalho que cause falecimento do empregado.',
    dataJulgamento: 'Abril/2025',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Direito Processual do Trabalho',
    tags: ['prescrição', 'dano moral', 'ricochete', 'indenização', 'Código Civil'],
    relator: 'Ministro Relator',
    metaDescription: 'Tema 126 do TST: Prescrição trienal (CC) para dano moral em ricochete na Justiça do Trabalho.',
  },
  {
    id: 'incidente-adesao-2024',
    titulo: 'IRR - Horas Extras e Banco de Horas (Tema 23)',
    tema: 'IRR - Incidente de Recurso Repetitivo',
    tese: 'O banco de horas instituído por acordo individual, nos termos da Reforma Trabalhista de 2017, é válido para compensação em até 6 meses, desde que haja controle e registro das horas.',
    descricao: 'Em julgamento de Incidente de Recurso Repetitivo, o TST reafirmou a validade do banco de horas instituído por acordo individual escrito, nos termos do art. 59, §5º e §6º da CLT (redação da Lei 13.467/2017). A compensação pode ser feita em até 6 meses, com controle e registro das horas trabalhadas. Se a compensação não ocorrer no prazo, as horas devem ser pagas como extras. O banco de horas por acordo coletivo pode ter prazo de até 1 ano.',
    dataJulgamento: '2024',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Jornada e Condições de Trabalho',
    tags: ['banco de horas', 'acordo individual', 'jornada 12x36', 'compensação'],
    metaDescription: 'IRR TST: Banco de horas por acordo individual é válido para compensação em até 6 meses. Art. 59 CLT.',
  },
  {
    id: 'tema-1046-stf',
    titulo: 'Tema 1046 STF - Negociado sobre o Legislado',
    tema: 'Tema 1046 - Repercussão Geral STF',
    tese: 'São válidas as normas coletivas que limitam ou suprimem direitos trabalhistas, desde que não sejam direitos absolutamente indisponíveis.',
    descricao: 'O Supremo Tribunal Federal, no julgamento do Tema 1046 (RE 1.476.596), fixou a tese de que são válidas as normas coletivas de trabalho que limitam ou afastam direitos trabalhistas, desde que não se refiram a direitos absolutamente indisponíveis (como salário mínimo, FGTS, férias + 1/3, licença-maternidade, etc.). A decisão consolida o entendimento de que a negociação coletiva tem prevalência sobre a lei em diversos temas, conforme a Reforma Trabalhista de 2017. O STF também validou a redução do intervalo intrajornada por acordo coletivo (Tema 1046).',
    dataJulgamento: '2023/2024',
    orgaoJulgador: 'Supremo Tribunal Federal - Plenário',
    categoria: 'Jornada e Condições de Trabalho',
    tags: ['negociado sobre legislado', 'STF', 'acordo coletivo', 'intervalo', 'direitos indisponíveis'],
    relator: 'Ministro Gilmar Mendes',
    metaDescription: 'Tema 1046 STF: Validade de normas coletivas que limitam direitos trabalhistas, desde que não absolutamente indisponíveis.',
  },
  {
    id: 'tema-152',
    titulo: 'Tema 152 - Multa por Embargos Protelatórios',
    tema: 'Tema 152 - Recurso de Revista Repetitivo',
    tese: 'A multa por embargos protelatórios deve ser aplicada com moderação, apenas quando caracterizada a intenção de procrastinar o andamento processual.',
    descricao: 'O TST estabeleceu que a multa prevista no art. 1.026, §2º do CPC (aplicável subsidiariamente ao processo do trabalho) por interposição de embargos de declaração protelatórios deve ser aplicada com moderação, apenas quando restar comprovada a intenção deliberada de procrastinar o andamento processual. A mera repetição de argumentos já analisados não configura, por si só, intuito protelatório.',
    dataJulgamento: '2024',
    orgaoJulgador: 'Tribunal Pleno do TST - SDI-1',
    categoria: 'Direito Processual do Trabalho',
    tags: ['embargos protelatórios', 'multa', 'CPC', 'processo do trabalho'],
    metaDescription: 'Tema 152 do TST: Multa por embargos protelatórios deve ser aplicada com moderação, só com intenção comprovada de procrastinar.',
  },
];
