import type { OJ } from './types';

export const ojCategorias = [
  { id: 'jornada-remuneracao', name: 'Jornada e Remuneração' },
  { id: 'contrato-rescisao', name: 'Contrato e Rescisão' },
  { id: 'adicionais', name: 'Adicionais e Benefícios' },
  { id: 'processual', name: 'Direito Processual' },
];

export const ojs: OJ[] = [
  {
    id: 'oj-394-sdi1',
    numero: 394,
    titulo: 'OJ 394 da SDI-1 do TST - Horas Extras Habituais',
    conteudo: 'A média das horas extras habituais deve integrar o cálculo das férias, do 13º salário e do aviso prévio, calculada com base no valor total das horas extras recebidas nos 12 meses anteriores ao período aquisitivo de férias ou ao mês do aviso prévio ou do 13º salário. A integração deve ser feita pelo valor total das horas extras, incluindo o adicional e os reflexos no DSR.',
    categoria: 'Jornada e Remuneração',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1 (Subseção de Dissídios Individuais 1)',
    tags: ['horas extras', 'média', 'férias', '13º salário', 'aviso prévio'],
    metaDescription: 'OJ 394 SDI-1 TST: Média das horas extras habituais integra o cálculo de férias, 13º salário e aviso prévio.',
  },
  {
    id: 'oj-97-sdi1',
    numero: 97,
    titulo: 'OJ 97 da SDI-1 do TST - Adicional de Transferência',
    conteudo: 'O adicional de transferência previsto no art. 469, §3º da CLT é devido enquanto durar a transferência provisória do empregado para local diverso do que foi contratado, correspondendo a 25% do salário. O adicional não é devido quando a transferência for definitiva, salvo se houver alteração prejudicial ao empregado.',
    categoria: 'Adicionais e Benefícios',
    dataAprovacao: 'Res. 121/2003, DJ 19, 20 e 21.11.2003',
    secao: 'SDI-1',
    tags: ['adicional de transferência', 'art. 469 CLT', '25%', 'mudança de local'],
    metaDescription: 'OJ 97 SDI-1 TST: Adicional de transferência de 25% devido durante transferência provisória. Art. 469, §3º CLT.',
  },
  {
    id: 'oj-101-sdi1',
    numero: 101,
    titulo: 'OJ 101 da SDI-1 do TST - Multa do Art. 477 da CLT',
    conteudo: 'A multa prevista no art. 477, §8º da CLT é devida quando o pagamento das verbas rescisórias for efetuado fora do prazo legal de 10 dias, independentemente de o empregado ter sido previamente informado dos valores a receber. A multa corresponde a um salário do empregado e é devida mesmo na hipótese de o empregador entender que a rescisão ocorreu por justa causa.',
    categoria: 'Contrato e Rescisão',
    dataAprovacao: 'Res. 121/2003, DJ 19, 20 e 21.11.2003',
    secao: 'SDI-1',
    tags: ['multa art. 477', 'verbas rescisórias', 'prazo 10 dias', 'um salário'],
    metaDescription: 'OJ 101 SDI-1 TST: Multa do art. 477, §8º da CLT é devida quando pagamento das verbas rescisórias ocorre fora do prazo de 10 dias.',
  },
  {
    id: 'oj-115-sdi1',
    numero: 115,
    titulo: 'OJ 115 da SDI-1 do TST - Férias Vencidas',
    conteudo: 'O empregador que não concede as férias dentro do período concessivo deverá pagá-las em dobro, incluindo o valor do adicional de 1/3 constitucional. A dobra incide sobre o valor total das férias, ou seja, sobre o salário acrescido do 1/3 constitucional. O direito ao pagamento em dobro é devido independentemente de o empregado ter gozado ou não as férias.',
    categoria: 'Jornada e Remuneração',
    dataAprovacao: 'Res. 121/2003, DJ 19, 20 e 21.11.2003',
    secao: 'SDI-1',
    tags: ['férias em dobro', 'período concessivo', '1/3 constitucional', 'art. 137 CLT'],
    metaDescription: 'OJ 115 SDI-1 TST: Férias não concedidas no período concessivo devem ser pagas em dobro, incluindo 1/3 constitucional.',
  },
  {
    id: 'oj-173-sdi1',
    numero: 173,
    titulo: 'OJ 173 da SDI-1 do TST - Salário Mínimo e Jornada Reduzida',
    conteudo: 'O salário mínimo não pode ser proporcional à jornada reduzida se esta for inferior ao mínimo legal (8 horas diárias ou 44 horas semanais). O empregado contratado para jornada reduzida tem direito ao salário mínimo integral, salvo se houver previsão de proporcionalidade em acordo ou convenção coletiva.',
    categoria: 'Jornada e Remuneração',
    dataAprovacao: 'Res. 121/2003, DJ 19, 20 e 21.11.2003',
    secao: 'SDI-1',
    tags: ['salário mínimo', 'jornada reduzida', 'proporcionalidade'],
    metaDescription: 'OJ 173 SDI-1 TST: Salário mínimo integral é devido na jornada reduzida, salvo previsão em acordo coletivo.',
  },
  {
    id: 'oj-342-sdi1',
    numero: 342,
    titulo: 'OJ 342 da SDI-1 do TST - Descontos Fiscais e Previdenciários',
    conteudo: 'Os descontos fiscais e previdenciários devem ser calculados sobre o valor total da condenação, mês a mês, observando-se a competência de cada parcela e a alíquota vigente à época do fato gerador. A responsabilidade pelo recolhimento é do empregador, que deve comprovar nos autos o efetivo recolhimento dos valores descontados.',
    categoria: 'Direito Processual',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1',
    tags: ['descontos fiscais', 'IRRF', 'INSS', 'condenação', 'recolhimento'],
    metaDescription: 'OJ 342 SDI-1 TST: Descontos fiscais e previdenciários calculados mês a mês sobre valor total da condenação.',
  },
  {
    id: 'oj-245-sdi1',
    numero: 245,
    titulo: 'OJ 245 da SDI-1 do TST - Adicional de Periculosidade e EPI',
    conteudo: 'O adicional de periculosidade não é devido quando a utilização de Equipamentos de Proteção Individual (EPIs) é capaz de neutralizar o risco, desde que o empregador comprove o fornecimento adequado e a fiscalização efetiva do uso. O simples fornecimento do EPI não exclui o direito ao adicional se não houver comprovação de sua eficácia na neutralização do risco.',
    categoria: 'Adicionais e Benefícios',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1',
    tags: ['periculosidade', 'EPI', 'neutralização do risco', 'NR-16'],
    metaDescription: 'OJ 245 SDI-1 TST: Adicional de periculosidade não é devido quando EPIs neutralizam o risco, com comprovação de fornecimento e fiscalização.',
  },
  {
    id: 'oj-351-sdi1',
    numero: 351,
    titulo: 'OJ 351 da SDI-1 do TST - Horas In Itinere e Transporte Público',
    conteudo: 'O tempo despendido pelo empregado em transporte fornecido pelo empregador ao local de trabalho de difícil acesso ou não servido por transporte público regular é computável na jornada de trabalho. A existência de transporte público regular em horário compatível com a jornada de trabalho do empregado elide o direito às horas in itinere.',
    categoria: 'Jornada e Remuneração',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1',
    tags: ['horas in itinere', 'transporte', 'jornada', 'local de difícil acesso'],
    metaDescription: 'OJ 351 SDI-1 TST: Horas in itinere são devidas quando local é de difícil acesso ou sem transporte público regular.',
  },
  {
    id: 'oj-397-sdi1',
    numero: 397,
    titulo: 'OJ 397 da SDI-1 do TST - Dispensa de Empregado Público',
    conteudo: 'A dispensa de empregado público (contratado mediante concurso público sob regime celetista) exige motivação, sob pena de nulidade. O ato de dispensa deve ser motivado, com indicação do motivo que a justifica, sendo vedada a dispensa imotivada. A motivação pode ser apresentada posteriormente em juízo, mas deve existir para validade do ato.',
    categoria: 'Contrato e Rescisão',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1',
    tags: ['empregado público', 'dispensa motivada', 'concurso público', 'nulidade'],
    metaDescription: 'OJ 397 SDI-1 TST: Dispensa de empregado público exige motivação, sob pena de nulidade.',
  },
  {
    id: 'oj-398-sdi1',
    numero: 398,
    titulo: 'OJ 398 da SDI-1 do TST - Estabilidade do Membro da CIPA',
    conteudo: 'O membro da CIPA (Comissão Interna de Prevenção de Acidentes) eleito, titular ou suplente, tem estabilidade provisória no emprego desde o registro da candidatura até 1 ano após o fim do mandato. A estabilidade também se aplica ao empregado que ocupa cargo de representante de empregados na CIPA, independentemente de ter sido eleito diretamente pelos empregados ou designado pelo empregador para compor a comissão.',
    categoria: 'Contrato e Rescisão',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1',
    tags: ['CIPA', 'estabilidade', 'mandato', 'candidatura', 'art. 165 CLT'],
    metaDescription: 'OJ 398 SDI-1 TST: Membro da CIPA tem estabilidade desde a candidatura até 1 ano após o mandato.',
  },
  {
    id: 'oj-400-sdi1',
    numero: 400,
    titulo: 'OJ 400 da SDI-1 do TST - Trabalho aos Domingos - Autorização',
    conteudo: 'O trabalho aos domingos, quando não houver folga compensatória, deve ser pago em dobro. A autorização para trabalho aos domingos deve constar de convenção coletiva ou acordo coletivo de trabalho. O trabalho aos domingos em atividades que, por sua natureza, exigem funcionamento contínuo (hospitais, transportes, indústria contínua) pode ser autorizado por lei específica.',
    categoria: 'Jornada e Remuneração',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1',
    tags: ['domingos', 'trabalho em domingos', 'folga compensatória', 'pagamento em dobro'],
    metaDescription: 'OJ 400 SDI-1 TST: Trabalho aos domingos sem folga compensatória deve ser pago em dobro. Autorização em convenção coletiva.',
  },
  {
    id: 'oj-404-sdi1',
    numero: 404,
    titulo: 'OJ 404 da SDI-1 do TST - Jornada 12x36 - Feriados',
    conteudo: 'Na jornada 12x36, o empregado não tem direito ao pagamento em dobro pelo trabalho em feriados, desde que o regime de trabalho seja previsto em acordo ou convenção coletiva e o empregado usufrua de folgas em outros dias que compensem os feriados trabalhados. O regime 12x36 já contempla a compensação de domingos e feriados no ciclo de trabalho.',
    categoria: 'Jornada e Remuneração',
    dataAprovacao: 'DEJT divulgado em 27.05.2011',
    secao: 'SDI-1',
    tags: ['jornada 12x36', 'feriados', 'compensação', 'acordo coletivo'],
    metaDescription: 'OJ 404 SDI-1 TST: Jornada 12x36 não gera direito a pagamento em dobro por feriados, se prevista em acordo coletivo.',
  },
  {
    id: 'oj-410-sdi1',
    numero: 410,
    titulo: 'OJ 410 da SDI-1 do TST - Multa do Art. 477 e Acordo Extrajudicial',
    conteudo: 'A multa prevista no art. 477, §8º da CLT não é devida quando há acordo extrajudicial para rescisão contratual, homologado pelo sindicato ou pelo Ministério do Trabalho, no qual as partes estipulem prazo diverso para pagamento das verbas rescisórias. A multa é afastada porque o prazo foi ajustado entre as partes com assistência sindical.',
    categoria: 'Contrato e Rescisão',
    dataAprovacao: 'DEJT divulgado em 22.06.2016',
    secao: 'SDI-1',
    tags: ['multa art. 477', 'acordo extrajudicial', 'homologação', 'sindicato'],
    metaDescription: 'OJ 410 SDI-1 TST: Multa do art. 477 não é devida quando há acordo extrajudicial homologado pelo sindicato com prazo diverso.',
  },
  {
    id: 'oj-417-sdi1',
    numero: 417,
    titulo: 'OJ 417 da SDI-1 do TST - Aviso Prévio e Gratificação de Função',
    conteudo: 'O aviso prévio indenizado integra o tempo de serviço do empregado para todos os efeitos legais, inclusive para cálculo da gratificação de função. O período do aviso prévio, ainda que indenizado, deve ser considerado para a contagem do tempo de serviço que serve de base para a concessão de benefícios e vantagens previstos em regulamento empresarial.',
    categoria: 'Contrato e Rescisão',
    dataAprovacao: 'DEJT divulgado em 22.06.2016',
    secao: 'SDI-1',
    tags: ['aviso prévio indenizado', 'tempo de serviço', 'gratificação de função'],
    metaDescription: 'OJ 417 SDI-1 TST: Aviso prévio indenizado integra tempo de serviço para todos os efeitos, inclusive gratificação de função.',
  },
  {
    id: 'oj-423-sdi1',
    numero: 423,
    titulo: 'OJ 423 da SDI-1 do TST - Comissão de Representantes de Empregados',
    conteudo: 'O representante de empregados eleito em empresas com mais de 200 funcionários, nos termos do art. 510-B da CLT (incluído pela Reforma Trabalhista de 2017), tem estabilidade provisória no emprego desde o registro da candidatura até 1 ano após o fim do mandato, não podendo ser dispensado sem justa causa durante esse período.',
    categoria: 'Contrato e Rescisão',
    dataAprovacao: 'DEJT divulgado em 22.06.2016',
    secao: 'SDI-1',
    tags: ['comissão de empregados', 'estabilidade', 'art. 510-B CLT', 'representante'],
    metaDescription: 'OJ 423 SDI-1 TST: Representante de empregados (art. 510-B CLT) tem estabilidade desde a candidatura até 1 ano após o mandato.',
  },
  {
    id: 'oj-424-sdi1',
    numero: 424,
    titulo: 'OJ 424 da SDI-1 do TST - Trabalho Intermitente e Verbas Rescisórias',
    conteudo: 'No contrato de trabalho intermitente (art. 443, §3º e 452-A da CLT), as verbas rescisórias são calculadas proporcionalmente ao período de efetivo trabalho, considerando-se como tempo de serviço apenas os períodos em que houve prestação de serviço. O empregado tem direito a férias proporcionais, 13º proporcional e FGTS sobre os valores recebidos durante o período de trabalho.',
    categoria: 'Contrato e Rescisão',
    dataAprovacao: 'DEJT divulgado em 22.06.2016',
    secao: 'SDI-1',
    tags: ['trabalho intermitente', 'verbas rescisórias', 'art. 452-A CLT'],
    metaDescription: 'OJ 424 SDI-1 TST: Verbas rescisórias no contrato intermitente são proporcionais ao período de trabalho efetivo.',
  },
];
